### ISSUE TITLE
Feature request: yum package

### ISSUE THREAD

**Issue by janbrogger** [SamSchott/maestral#27] opened 2019-07-20 23:52 UTC
The GUI hangs, so I have to run it on command line. Details below.

Request a package that can be installed with a package manager like so:
`sudo yum install maestral-dropbox`

I had to install it in a slightly complicated way (CentOS 7):
**Install Python**
`sudo yum install -y libgnome centos-release-scl rh-python36`
`#wrong python version by default`
`python --version`
`#fix new python version`
`scl enable rh-python36 bash`
`python --version`

**Install Maestral** 
`sudo yum install -y python36-setuptools`
`sudo easy_install-3.6 pip`
`python3 -m pip install --upgrade maestral --user`
`python3 -m pip install --upgrade PyQt5 --user`
**Run Maestral GUI which often hangs**
`~/.local/bin/maestral gui`
#may fail
#set up Dropbox account then quit
**This command-line way works**
`~/.local/bin/maestral configure`
`~/.local/bin/maestral sync`

**Comment by SamSchott** [comment] 2019-07-21 10:46
Uh, this is indeed a difficult install process. I would not be surprised if the lagging UI has something to do with it.

I have only tested Maestral on Fedora 29 and CentOS 6, though it seems to run without problems on Fedora 30 as well. For CentOS 6, I have had very good experiences with the following setup:

- Install [anaconda python](https://www.anaconda.com/distribution/) or [miniconda](https://docs.conda.io/en/latest/miniconda.html).
- Install PyQt5, conda will provide PyQt 5.9: `conda install pyqt`
- Install Maestral: `pip3 install --upgrade maestral`

Binary packages for Linux are planned for the future, but I don't have any experience with Linux  packing and the large number of distributions complicates things. I am hoping that Maestral users on the respective platforms are willing to help out.

**Comment by SamSchott** [comment] 2019-07-21 12:01
May I ask, at which stage does GUI hang? I have just installed Maestral on CentOS 7 using the above setup and cannot see any problems.

**Comment by ahydronous** [comment] 2019-11-14 15:17
@SamSchott packaging with Snap or Flatpak could be a good option. Eventually you could distribute Maestral on Linux via the Snap store / Flathub and on macOS via homebrew!

**Comment by arkenoi** [comment] 2020-03-18 08:40
For me GUI did not work at all (Fedora 30)

▲ ~ python3 --version                                                                              
Python 3.7.6

▲ ~ maestral gui                                                                                   
No maestral GUI installed. Please run 'pip3 install maestral[gui]'.

▲ ~ pip3 install --user --upgrade maestralgui                                                      
Collecting maestralgui
  Could not find a version that satisfies the requirement maestralgui (from versions: )
No matching distribution found for maestralgui

PyQt5 is upgraded to up to date version.

**Comment by SamSchott** [comment] 2020-03-18 18:23
@arkenoi, you will need to run the command with brackets:

```shell
pip3 install --user --upgrade maestral[gui]
```

**Comment by arkenoi** [comment] 2020-03-20 11:30
Ah, got that. So I installed the GUI and it does, indeed, hang. Can I be of any help to diagnose the problem further?

**Comment by SamSchott** [comment] 2020-03-20 19:10
To troubleshot:

1. Does the daemon alone work?
2. If yes, what does `maestral status` return after you have started it?
3. What happens if you start syncing first and then run the gui to attach to the daemon?

**Comment by arkenoi** [comment] 2020-03-27 09:46
Ah, turns out it actually DOES start. It just shows tiny black on black icon you won't notice if you do not pay attention to a mysterious empty space in the notification bar :) When I click it, the GUI is there. Probably a dark theme issue.

**Comment by SamSchott** [comment] 2020-03-27 12:03
That is strange, I see no such issues in Fedora 30 myself. Could you check if the icons have been correctly installed?

If you have installed maestral globally, a set of status bar icons should be located at `/usr/local/share/icons/hicolor/scalable/status`, for instance `maestral-icon-idle-symbolic.svg`. If you have installed for the current user only, the location is `~/.local/share/icons/hicolor/scalable/status`. If icons cannot be found there, e.g., because Maestral was installed in a virtual environment, it falls back to loading the icon files through Qt.  In this case, there is a known issue with icons being tiny on hi-dpi screens.

**Comment by SamSchott** [comment] 2020-03-27 12:12
You can always manually download the icons, copy them to `~/.local/share/icons/hicolor/scalable/status` and update the icons cache with

```shell
$ sudo update-icon-caches ~/.local/share/icons/*
```

The svg files are available from [maestral-qt](https://github.com/SamSchott/maestral-qt/tree/master/maestral_qt/resources/tray-icons-gnome).

**Comment by arkenoi** [comment] 2020-03-29 09:42
The icons are in place at ~/.local/share/icons/hicolor/scalable/status. I run mate in dark mode and there is just a black empty space. Which package provides update-icon-caches? I do not have it.

**Comment by SamSchott** [comment] 2020-03-29 16:01
This seems to be more complicated than I initially thought. Could you open a new issue with information about your PyQt version, desktop environment etc? There is an issue template which should be helpful. Then I can try and reproduce this.

**Comment by arkenoi** [comment] 2020-04-04 15:34
The latest update fixed the problem, thanks!

**Comment by SamSchott** [comment] 2020-12-09 12:51
Closing this since a yum package is not planned. In the mid term, the goal is to provide an AppImage for all Linux distributions.

**Closed by SamSchott** 2020-12-09 12:51 UTC
Labels: feature request
