### ISSUE TITLE
Maestral not starting - unable to create the socket?

### ISSUE THREAD

**Issue by uslacker99** [samschott/maestral#330] opened 2021-02-19 22:04 UTC
**Describe the bug**

Maestral doesn't seem to be starting. In doing an strace, it shows:
```
newfstatat(AT_FDCWD, "/run/user/1001", {st_mode=S_IFDIR|0700, st_size=180, ...}, 0) = 0
mkdirat(AT_FDCWD, "/run/user/1001/maestral", 0777) = -1 EEXIST (File exists)
newfstatat(AT_FDCWD, "/run/user/1001/maestral", {st_mode=S_IFDIR|0775, st_size=60, ...}, 0) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1001/maestral/maestral.sock"}, 39) = -1 ENOENT (No such file or directory)
close(3)                                = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=200000000}, NULL) = 0 (Timeout)
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1001/maestral/maestral.sock"}, 39) = -1 ENOENT (No such file or directory)
close(3)                                = 0
pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=200000000}, NULL) = 0 (Timeout)
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC, 0) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1001/maestral/maestral.sock"}, 39) = -1 ENOENT (No such file or directory)
close(3)                                = 0
```

**To Reproduce**

I'm running Ubuntu 20.10 Groovy Gorilla on ARM. Python 3.8.6

**Expected behaviour**

**System:**

 - Maestral version: 1.4.2
 - OS: [e.g. Ubuntu] Ubuntu 20.10
 - Desktop environment: [e.g. Gnome 3.32] headless
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by uslacker99** [comment] 2021-02-19 22:06
strace output attached.

Thanks!

[maestral.strace.out.gz](https://github.com/SamSchott/maestral/files/6013197/maestral.strace.out.gz)

**Comment by uslacker99** [comment] 2021-02-19 22:11
maestral log show 
gives me:
2021-02-19 13:24:12 maestral.sync INFO: Connected
2021-02-19 13:40:01 maestral.sync DEBUG: Could not load mignore rules from /home/Colossus/Dropbox/.mignore: [Errno 2] No such file or directory: '/home/Colossus/Dropbox/.mignore'
2021-02-19 13:40:01 maestral.sync INFO: Connected
2021-02-19 13:51:55 maestral.sync INFO: Connected
2021-02-19 13:56:48 maestral.sync INFO: Connected

alton@ubuntu:~$ cat ~/.config/maestral/maestral.ini
[main]
path = /home/Colossus/Dropbox
excluded_items = []
version = 15.0.0

[account]
account_id = dbid:AAAyzz13xxxxxxxLhy-jr7xRxKxX38E

[app]
notification_level = 15
log_level = 20
update_notification_interval = 604800
keyring = keyrings.alt.file.PlaintextKeyring

[sync]
reindex_interval = 1209600
max_cpu_percent = 20.0
keep_history = 604800
upload = True
download = True

Thanks!

**Comment by uslacker99** [comment] 2021-02-19 22:19
strace -fa if it helps. :)
[maestral.strace.out.gz](https://github.com/SamSchott/maestral/files/6013275/maestral.strace.out.gz)

**Comment by SamSchott** [comment] 2021-02-19 23:02
It look like the daemon is starting but the CLI cannot communicate with it properly over the created socket. Could try starting the process in the foreground and in verbose mode with `maestral start -f -v`? Does this raise any errors? If it doesn't, what does running `maestral status` in other terminal return?

**Comment by uslacker99** [comment] 2021-02-19 23:28
It works!

alton@ubuntu:~$ /usr/local/bin/maestral start -f -v
2021-02-19 15:22:59 maestral.sync INFO: Connected
2021-02-19 15:22:59 maestral.sync INFO: Connected
2021-02-19 15:23:02 maestral.sync INFO: Indexing remote Dropbox
2021-02-19 15:23:56 maestral.sync INFO: Indexing 500...
2021-02-19 15:23:56 maestral.sync INFO: Syncing ↓ 1/500 

-----

alton@ubuntu:/home/Colossus/Dropbox$ maestral status

Account:      alton@shocknetwork.com (Basic)
Usage:        30.2% of 23.5 GB used
Status:       Creating folders...
Sync errors:  0

**Comment by SamSchott** [comment] 2021-02-20 01:13
Nice! I'm still confused as to why the regular command didn't work. Is it still failing to connect to the socket?

**Comment by uslacker99** [comment] 2021-02-20 01:19
It still fails to socket, but works fine in the foreground. :)

**Comment by FransUrbo** [comment] 2021-11-23 11:18
I'm running v1.5.1 and the `maestral start -f -v` did not work for me.. It just sat there "Starting daemon.."

**Comment by FransUrbo** [comment] 2021-11-23 12:07
Running with `log_level = 1`, I see this in the log:
```
2021-11-23 11:58:19 daemon DEBUG: Acquired daemon lock: '/home/turbo/.cache/maestral/maestral.lock'
2021-11-23 11:58:19 daemon DEBUG: Socket path: '/home/turbo/.cache/maestral/maestral.sock'
2021-11-23 11:58:19 daemon DEBUG: Creating Pyro daemon
2021-11-23 11:58:19 sync DEBUG: Could not load mignore rules: No such file or directory
2021-11-23 11:58:36 daemon ERROR: Could not communicate with daemon
[because it can't find the socket file]
```

Comparing that with the code:
```
        dlogger.debug("Creating Pyro daemon")

        maestral_daemon = expose(Maestral)(config_name, log_to_stderr=log_to_stderr)

        dlogger.debug("Starting event loop")
```

So it's not going into the event loop. My Python is extremely rusty (and it wasn't that good to begine with :), so I'm not sure what the problem is..

**Comment by FransUrbo** [comment] 2021-11-23 12:35
So running with `maestral start -f -v` (which didn't work initially, but apparently works now!??), it does create the socket and I see:
```
2021-11-23 12:33:38 daemon DEBUG: Acquired daemon lock: '/home/turbo/.cache/maestral/maestral.lock'
2021-11-23 12:33:38 daemon DEBUG: Socket path: '/home/turbo/.cache/maestral/maestral.sock'
2021-11-23 12:33:38 daemon DEBUG: Creating Pyro daemon
2021-11-23 12:33:38 sync DEBUG: Could not load mignore rules: No such file or directory
2021-11-23 12:33:38 daemon DEBUG: Starting event loop
2021-11-23 12:33:38 oauth DEBUG: Using keyring: keyrings.alt.file.PlaintextKeyring (priority: 0.5)
2021-11-23 12:33:38 manager INFO: Connected
```

**Comment by samschott** [comment] 2023-05-16 20:12
Closing since this (1) seems to be resolved now and (2) daemon communication reliability saw many improvements since back then.

**Closed by samschott** 2023-05-16 20:12 UTC
Labels: bug
