### ISSUE TITLE
 No maestral GUI installed. Please run 'pip3 install maestral[gui]'.

### ISSUE THREAD

**Issue by rorymullen** [SamSchott/maestral#280] opened 2021-01-18 12:10 UTC
**Describe the bug**
Noob here. I'm trying to install maestral on a new M1 mac mini. I have run the following commands in terminal:

`python3 -m pip install --upgrade maestral`,

then

`python3 -m pip install --upgrade maestral-cocoa`.

Four Maestral folders appears in Finder in the python 3.9 site-packages folder /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/

Folder 1. maestral
Folder 2. maestral_cocoa
Folder 3. maestral_cocoa-1.3.0.dist-info
Folder 4. maestral-1.3.1.dist-info

When I issue the command `maestral gui` in terminal, I get

`! No maestral GUI installed. Please run 'pip3 install maestral[gui]'.`.

This is odd because the GUI appears to already be installed, as far as I can tell from the site-packages folder. But again: I'm a complete noob. Running `pip3 install maestral-cocoa` then gives me a few lines of console output of the form:

`Requirement already satisfied: maestral-cocoa in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.3.0)`

Also, the Maestral app does not appear in my /Applications folder. I'm sure I'm doing something stupid here, any ideas? 

**Expected behaviour**
I expected a GUI to open...

**System (please complete the following information):**
 - Maestral version: 1.3.1
 - OS: MacOS Big Sur 11.1

**Additional context**
Running `which python3` yields `/usr/local/bin/python3`, and `python3 --version` yields `Python 3.9.1`. Running `which pip3` yields `/usr/local/bin/pip3`, and `pip3 --version` yields

`pip 20.3.3 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)`. 

I have also run `alias python=/usr/local/bin/python3` based on advice [here](https://stackoverflow.com/questions/37341614/modules-are-installed-using-pip-on-osx-but-not-found-when-importing).

**Comment by SamSchott** [comment] 2021-01-18 16:58
This is indeed odd, your site-packages indicate that the GUI has been installed correctly. The GUI will also install its own command line entry point `maestral_cocoa`. Does running this command work? Or does it fail with `zsh: command not found` or a Python ImportError?

> Also, the Maestral app does not appear in my /Applications folder.

That's expected for a pip-install. None of your other Python packages show up in the Applications folder either. Alternatively, you can download the app bundle (dmg) from the [releases](https://github.com/SamSchott/maestral/releases) page. This will give you a regular Mac app instead of a Python package. I am not sure if it will run on a M1 Mac though. If you try it out, please let me know!

**Comment by SamSchott** [comment] 2021-01-18 17:01
A side-node regarding M1 support: proper universal binaries will need to wait until [briefcase](https://github.com/beeware/briefcase), which is used for macOS packaging, supports them. My hope for now is that the app bundle will work with Rosetta translation.

**Comment by rorymullen** [comment] 2021-01-18 17:10
Thanks for the quick response (and for this excellent application). Running `maestral_cocoa` worked like a charm!

Thanks again!

**Comment by SamSchott** [comment] 2021-01-18 17:56
I'm glad it's working :) If you do get a chance to try the app bundle, let me know how it goes. I don't have access to a M1 mac myself.

**Comment by rorymullen** [comment] 2021-01-27 18:38
Apologies for the slow reply. I installed the Maestral app bundle with no trouble, seems to work beautifully on Apple silicon (through Rosetta 2). Uses 1/2, maybe 1/3 of the memory that Dropbox was using.

Thank you again, amazing app, you're a hero! Looking forward to the native Apple silicon build :)

**Comment by SamSchott** [comment] 2021-01-28 22:28
No worries, I'm glad to hear its working! The native build may be a while away, but there will be significant improvements to memory usage from updates to two core dependencies in the meantime ([rubicon-objc](https://github.com/beeware/rubicon-objc) and [watchdog](https://github.com/gorakhargosh/watchdog)).

**Comment by SamSchott** [comment] 2021-02-14 19:32
Closing. The issue isn't directly caused by Maestral but rather by the setup of the Python environment and can be solved by using the app bundle.

**Closed by SamSchott** 2021-02-14 19:32 UTC
