### ISSUE TITLE
Saving an excel file deletes it from other locations (macOS Mojave only)

### ISSUE THREAD

**Issue by pfascia** [samschott/maestral#381] opened 2021-05-05 09:17 UTC
**Describe the bug**
 Saving a modified excel file causes it is removed from other synced location, with the message xxxx.xls was removed.. It remains in the location where it has been saved, and it is not synced anymore to the other dropbox location

**To Reproduce**
 put an excel file in a dropbox folder synced and then open it and save. It will be removed from other location, not in that where it has been saved

**Expected behaviour**
 file saved is synced to the other locations at every saved modification

**System:**
 macos Mojave, last version

 - Maestral version: 1.4.1
 - Python version: 
 - OS: [e.g. Ubuntu] macOs Mojave 
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by SamSchott** [comment] 2021-05-05 09:38
This may be related to #337 which was fixed in the latest release. Could you update to v1.4.3 and check if the issue persists?

If it does, could you set the log level to DEBUG and post the log output from the related sync events?

**Comment by pfascia** [comment] 2021-05-05 09:41
Same with 1.4.3, how can I set the log level?

**Comment by SamSchott** [comment] 2021-05-05 09:49
Oh, that is strange. I could not reproduce this on Big Sur with Excel 16.48 and therefore hoped that it would be already fixed. Which version of Excel are you using? They changed the way how file modifications are saved some time ago.

You can set the log level with the CLI command `maestral log level DEBUG` and then show the logs with `maestral log show -e` (documentation [here](https://www.maestral.app/cli/log)). If you are using the macOS app bundle, you'll need to install the command line tool first from the preference pane.

**Comment by pfascia** [comment] 2021-05-05 10:00
Excel is 16.48, 
[Untitled.txt](https://github.com/SamSchott/maestral/files/6426287/Untitled.txt)
log is appended

**Comment by SamSchott** [comment] 2021-05-05 10:04
Thanks! I'll have a closer look at it some time this week.

**Comment by pfascia** [comment] 2021-05-05 11:29
Thanks to You! I hope You'll find a solution.. :-)

**Comment by SamSchott** [comment] 2021-05-06 11:31
So, the situation seems to be a bit more complicated than expected. From the logs, it appears that the sync indeed receives a single deleted event:

```
2021-05-05 11:53:41 maestral.sync DEBUG: Retrieved local file events:
[<FileDeletedEvent: event_type=deleted, src_path='XXX.xlsx', is_directory=False>]
2021-05-05 11:53:41 maestral.sync DEBUG: Cleaned up local file events:
{<FileDeletedEvent: event_type=deleted, src_path='XXX.xlsx', is_directory=False>}
2021-05-05 11:53:42 maestral.sync DEBUG: Filtered local file events:
[<SyncEvent(direction=Up, change_type=Removed, item_type=ItemType.File, dbx_path='XXX.xlsx')>]
2021-05-05 11:53:42 maestral.sync INFO: Uploading deletions...
2021-05-05 11:53:43 maestral.sync INFO: Deleting 1/1...
2021-05-05 11:53:43 maestral.sync DEBUG: Local cursor saved: 1620208420.9928262
2021-05-05 11:53:43 maestral.sync INFO: Up to date
```

Since we are using the same version of Excel the difference might either lie in how Excel saves modifications in HFS+ vs APFS file systems or in how Mojave vs Big Sur report file system events. In any case, I'd need to see the reported native events which are currently not logged.

Are you using the Python package or the app bundle? If you are using the Python package, I can give you instructions to enable the log output. Otherwise, I can create a build that includes the log output from the interface to native APIs.

**Comment by pfascia** [comment] 2021-05-06 12:01
App bundle, Mojave, APSF

**Comment by pfascia** [comment] 2021-05-06 12:54
I'm now planning to switch to big sur, so it is not so urgent... don't worry

**Comment by SamSchott** [comment] 2021-05-07 18:34
Interesting, I can reproduce the Excel file being deleted when syncing from a Mojave virtual machine. So no need to debug it on your side.

> I'm now planning to switch to big sur, so it is not so urgent... don't worry

Oh, I am worried. Loss of data is pretty much the wort-case outcome for a sync client :( At least the issue does disappear after updating.

**Comment by pfascia** [comment] 2021-05-07 18:47
Thank You for your time, for the moment I deactivated maestral after the loose of some  work excels, (I took them back via the external backup).


Il giorno 7 mag 2021, alle ore 20:34, SamSchott ***@***.***> ha scritto:

﻿

Interesting, I can reproduce the Excel file being deleted when syncing from a Mojave virtual machine. So no need to debug it on your side.

I'm now planning to switch to big sur, so it is not so urgent... don't worry

Oh, I am worried. Loss of data is pretty much the wort-case outcome for a sync client :( At least the issue does disappear after updating.

**Comment by SamSchott** [comment] 2021-05-07 18:55
Looking at the file system stats, it appears that saving the changes takes place by deleting the old file and creating a new file at the same path but with a different inode. However, the native `FSEvents` API only reports a single "file moved" event with the *old* inode. Since that inode is nowhere to be found (no longer exists) when the save has completed, the file is assumed to be deleted or moved outside of the Dropbox folder.

It appears that this is indeed a bug in macOS which was fixed in a later release. I could work a round it by rescanning files manually to confirm any reported changes but I'm not particularly inclined to do so, especially since its no longer an issue with Big Sur. Such manual rescanning will likely at a performance cost, particularly when dealing with moves of entire folders.

**Comment by SamSchott** [comment] 2021-05-07 18:57
Apologies for the trouble that you went through!

**Comment by pfascia** [comment] 2021-05-07 18:59
Ok, thank You for the trying, but stop it, don’t loose more time for something that is fixed in other release and it is not your app fault

Inviato da iPhone

Il giorno 7 mag 2021, alle ore 20:56, SamSchott ***@***.***> ha scritto:

﻿

Looking at the file system stats, it appears that saving the changes takes place by deleting the old file and creating a new file at the same path but with a different inode. However, the native FSEvents API only reports a single "file moved" event with the old inode. Since that inode is nowhere to be found (no longer exists) when the save has completed, the file is assumed to be deleted or moved outside of the Dropbox folder.

It appears that this is indeed a bug in macOS which was fixed in a later release. I could work a round it by rescanning files manually to confirm any reported changes but I'm not particularly inclined to do so, especially since its no longer an issue with Big Sur. Such manual rescanning will likely at a performance cost, particularly when dealing with moves of entire folders.

**Comment by SamSchott** [comment] 2021-05-08 18:33
Ok, at least now I know what is causing the issue and why it's no longer present in Big Sur. This is already much more reassuring than an unexplained loss of data!

**Comment by samschott** [comment] 2023-05-16 20:16
Closing since Maestral officially no longer supports macOS Mojave.

**Closed by samschott** 2023-05-16 20:16 UTC
Labels: bug, wontfix, macOS
