### ISSUE TITLE
CLI throwing error; says can't find anything at given path, even when dragging file in from Finder window

### ISSUE THREAD

**Issue by theboyler** [samschott/maestral#765] opened 2022-11-30 16:49 UTC
I've been using Maestral for about 6 months, and not had any issues. I'd written two shortcuts which wrapped around applescripts to get the dropbox share link when right-clicking, and the dropbox file history.  These were working perfectly. 

I just went to use the first shortcut, and the command line is throwing the error "! Could not create shared link. There is nothing at the given path"; this is weird because the script used to work. 

I went into Terminal, and used the sharelink command, dropping the file into the terminal command by dragging it from Finder, and it throws the same error. 

Am using Ventura and Maestral 1.6.3

**Comment by samschott** [comment] 2022-12-04 12:33
`maestral sharelink` requires a path relative to the Dropbox directory. Dragging the file from Finder therefore does not work.

I'm surprised about your scripts though, you say that they used to work?

**Comment by ernstki** [comment] 2022-12-15 23:34
Seeing a similar issue with Maestral 1.6.5 on an Ubuntu 20.04-based Linux distribution (elementaryOS):

```console
$ ls -l ~/Dropbox/00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf 
-rw-rw-r-- 1 me me 108784 Dec 15 18:08 /home/me/Dropbox/00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf

$ maestral sharelink create ~/Dropbox/00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf 
! Could not create shared link. There is nothing at the given path.

$ maestral sharelink create 00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf 
! Could not create shared link. There is nothing at the given path.
```

**Comment by ernstki** [comment] 2022-12-15 23:34
Seeing a similar issue with Maestral 1.6.5 on an Ubuntu 20.04-based Linux distribution (elementaryOS):

```console
$ ls -l ~/Dropbox/00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf 
-rw-rw-r-- 1 me me 108784 Dec 15 18:08 /home/me/Dropbox/00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf

$ maestral sharelink create ~/Dropbox/00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf 
! Could not create shared link. There is nothing at the given path.

$ maestral sharelink create 00_INBOX/OSDC_cheatsheet-compose-2022.4.15.pdf 
! Could not create shared link. There is nothing at the given path.
```

**Comment by samschott** [comment] 2022-12-16 14:37
@ernstki, thanks for providing examples. The last command which you have posted should succeed. The `sharelink` command takes paths relative to the Dropbox folder as arguments so that it also works on items which are for example excluded by selective sync.

Could you confirm that the local file was indeed uploaded?

**Comment by ernstki** [comment] 2022-12-17 11:57
@samschott That's a good point. This was in the middle of an initial sync, which on my home wifi was… struggling with. There's a good chance _that_ particular file was fighting upstream against the thousands of other ones coming downstream.

The client probably did exactly the right thing under those circumstances, but the error message is just misleading. If you agree, that's something I could probably do a PR for (to make the error message more specific about which end "at the given path" is referring to).

**Comment by samschott** [comment] 2022-12-17 21:25
Sure, I'm happy to review PR to improve the usability!

In general, the CLI `--help` output distinguishes between `DROPBOX_PATH` and `LOCAL_PATH` arguments, but I acknowledge that the meaning of `DROPBOX_PATH` is not immediately clear without knowing about its counterpart LOCAL_PATH`.

For example, for `sharelink create`, the help output shows:

```
Usage: maestral sharelink create [OPTIONS] DROPBOX_PATH

  Create a shared link for a file or folder. Return the URL.

Options:
  -p, --password TEXT       Optional password for the link.
  -e, --expiry DATE         Expiry time for the link (e.g. '2025-07-24
                            20:50').
  -c, --config-name CONFIG  Run command with the given configuration.
  --help                    Show this message and exit.
```

**Comment by samschott** [comment] 2023-01-31 22:19
Closing this since it is working as intended. Feel free to open a separate issue or even a RP for documentation improvements.

**Closed by samschott** 2023-01-31 22:19 UTC
Labels: bug
