### ISSUE TITLE
`Application has crashed` on system login with two configs

### ISSUE THREAD

**Issue by LucianoLaratelli** [SamSchott/maestral#519] opened 2021-11-10 12:55 UTC
**Describe the bug**
I have two Maestral configurations. Both of these are set to start, with the GUI when I login to my system after booting it up. They crash immediately, both with the same traceback:
```
Traceback (most recent call last):
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 42, in <module>
  File "Contents/Resources/app_packages/maestral/daemon.py", line 91, in freeze_support
  File "Contents/Resources/app_packages/maestral/daemon.py", line 496, in start_maestral_daemon
  File "Contents/Resources/app_packages/maestral/daemon.py", line 202, in release
RuntimeError: Cannot release a lock, it was acquired by a different process
```
I should note that this doesn't appear to affect functionality; both Maestral instances are still running after these crash dialogues appear, and as far as I can tell they're syncing properly.

**To Reproduce**
Set up two Maestral configurations, both configured to start on login with the GUI.
Restart the machine. After logging in, observe the `Application has crashed` dialogue from each instance of Maestral that gets launched. 

**Expected behaviour**
I am able to boot into my machine with no error messages from Maestral on startup.

**System:**
 - Maestral version: GUI v1.5.1, daemon v1.5.1
 - Python version: 3.9.7
 - OS: macOS 12.0.1
 - Desktop environment: bundled with OS
 - PyQt version (for Linux GUI): n/a

**Comment by SamSchott** [comment] 2021-11-16 21:29
This may be a duplicate of #517. The problem there was that the GUI was set to start on login, as was the daemon independently through the CLI (maestral autostart -Y). In this case, there can be a race to start the daemon and only one of the two will succeed.

Could you check if this is the case? If yes, it certainly should be handled more gracefully than an error dialog since, as you note, an instance of the sync daemon is still started.

**Closed** 2021-11-17 08:28 UTC
Labels: bug, daemon
