### ISSUE TITLE
Authentication failed  Please make sure that you entered the correct authentication code.

### ISSUE THREAD

**Issue by tjluoma** [samschott/maestral#479] opened 2021-10-20 00:44 UTC
**Describe the bug**

I keep seeing an alert box telling me

![](https://images.luo.ma/temp/maestral-2021-10-19.png)

Authentication failed  Please make sure that you entered the correct authentication code.

I think this is actually being caused by an issue with the Dropbox API, because the app has been working fine and authorized for a long time now.

When it happens, maestral pauses.

**To Reproduce**

I don’t know how to make it happen but I have seen it repeatedly today.

**Expected behaviour**

No such error message

**System:**

 - Maestral version: 150 (35)
 - Python version: Python 3.9.7
 - OS: [e.g. Ubuntu] macOS version 12.0.1 (21A558)
 - Desktop environment: macOS version 12.0.1 (21A558)
 - PyQt version (for Linux GUI): n/a

**Additional context**

This happened on both my M1 Mac mini and MacBook Air. Both running the same version of macOS (which is Monterey beta, to be clear)

**Comment by dunkoh** [comment] 2021-10-20 02:23
Started having the same issue today as well.

Version 1.5.0 (35)
Mac OS 11.6 (20G165)

**Comment by duncanbrook** [comment] 2021-10-20 04:13
Same.  Trying to download a relatively small existing Dropbox folder on initial setup is now nearly impossible: I keep manually resuming sync, seeing a little progress, and then seeing the authentication error again.

**Comment by dantsai** [comment] 2021-10-20 04:15
Same here; I tried re-authenticating into Dropbox; it succeeds, then some minutes later, I get the error in the OP's screenshot.

**Comment by SamSchott** [comment] 2021-10-20 08:16
This appears to be glitch with Dropbox servers occasionally rejecting valid access tokens. I've reported the issue and they are investigating.

**Comment by duncanbrook** [comment] 2021-10-20 23:46
> @SamSchott Is there a better work-around than resuming sync manually at each authentication fail?

I asked roughly the same question a bit earlier and think @SamSchott already may have [addressed it in the next version](https://github.com/SamSchott/maestral/commit/958b4d72fc877fbced945c4450abc526872cb0b7)?

**Comment by EdogawaKun** [comment] 2021-10-21 11:28
Seems like the issue is solved at this moment.

**Comment by samschott** [comment] 2023-05-16 20:29
Closing since this was likely a temporary issue on the Dropbox side.

**Closed by samschott** 2023-05-16 20:29 UTC
Labels: bug
