### ISSUE TITLE
Always allow editing excluded list, not just when idle

### ISSUE THREAD

**Issue by Hubro** [samschott/maestral#958] opened 2023-08-08 09:59 UTC
**Is your feature request related to a problem? Please describe.**

I wanted to install Maestral with selective sync, since i only wanted 2-3 folders out of my 30+.

However, during the initial setup, when selecting which folders to sync, I accidentally pressed "Enter" when I tried to check my folders, which proceeded with 0 folders selected.

Maestral now went into "Indexing..." status, during which I wasn't allowed to edit the excluded folders list.

```
$ maestral excluded remove /personal
! Cannot include item. Please try again when idle.
```

This is extremely frustrating, because I know indexing may take a *long* time, maybe hours?

I come back the next day, indexing is done. Ideally I would have all my folders synced by now, but I wasn't allowed to edit the excluded list.

I try to remove the folders I want from the excluded list:

```
$ maestral excluded remove /personal /images /dotfiles
Error: Got unexpected extra arguments (/images /dotfiles)
```

No way... Please don't tell me...

```
$ maestral excluded remove /personal
✓ Included '/personal'. Now downloading...
$ maestral excluded remove /images
! Cannot include item. Please try again when idle.
```

No... NOOO! I actually have to finish syncing 1 directory at a time, then come back and remove another one from the excluded list? This is going to take *ages*.

**Describe the solution you'd like**

The excluded list should always be editable, or at the very least multiple edits should be possible at the same time, so I don't have to spend hours or days slowly editing my config.

**Describe alternatives you've considered**

Don't fuck up the initial setup... Hopefully I won't next time.

**Additional context**

**Comment by samschott** [comment] 2024-03-24 12:25
Passing multiple items to `maestral excluded add | remove` is now supported. Regarding modifying this list while indexing and syncing, this is a duplicate of #958.

**Closed by samschott** 2024-03-24 12:25 UTC
Labels: enhancement

**Comment by RokeJulianLockhart** [comment] 2024-03-24 13:17
> https://github.com/samschott/maestral/issues/958#issuecomment-2016792961

@samschott, you've linked https://github.com/samschott/maestral/issues/958#issue-1840988001, this issue, as a duplicate of itself. XD

**Comment by samschott** [comment] 2024-03-24 14:41
Argg, I meant to link #303.
