### ISSUE TITLE
conflicting copy and no upload

### ISSUE THREAD

**Issue by Access-deny** [samschott/maestral#869] opened 2023-04-03 11:36 UTC
**Describe the bug**
Hello.
I'm not sure if this is a bug. Perhaps I'm doing something wrong. The official dropbox refused after v.170 to work because of the glibc version and not work anymore.
maestral stubbornly downloads files from the cloud, ignores the settings. Unable to upload existing files to the cloud.
So always local copies -
sync DEBUG: Local item ".tar.gz" has unsynced local changes: conflict
sync DEBUG: Download conflict: renamed "" to ".tar (conflicting copy).gz"
sync DEBUG: Rescanning ".tar (conflicting copy).gz"
Tried changing settings:
upload = False
download = True
(maestral download files from the cloud)
and
upload = True
download = False
(maestral download files from the cloud)...
Not a single byte has been uploaded to the cloud. How to make it upload files to the cloud?

**To Reproduce**
Only start daemon with already exist files on both sides (dropbox cloud - old files with history version and server - new files).

Today newlog after "rebuild-index":
2023-04-03 12:48:30 sync INFO: Syncing ↓ 254/500
2023-04-03 12:48:30 sync DEBUG: Local item "any_file.tar.gz" has unsynced local changes: conflict
2023-04-03 12:48:30 sync DEBUG: Local item "any_file.tar.gz" has unsynced local changes: conflict
2023-04-03 12:48:30 sync DEBUG: Download conflict: renamed "any_file.tar.gz" to "any_file.tar (conflicting copy).gz"
...
As a result:
in the cloud are files dated March 19th. On the server, new ones are already dated April 2. Maestral downloads the file filename.tar.gz from the cloud to the server March 19, and renames the new file on the server on April 2 to $filename.tar (conflicting copy).gz.

**Expected behaviour**
Replacing files in the dropbox cloud with new ones downloaded from the file server. I need to upload files to the cloud, not download them. Also, I cannot delete files in the cloud, they are needed to view their versions.

**System:**
Centos 7 without GUI 
3.10.0-1160.71.1.el7.x86_64
Python 3.8.16
maestral 1.7.1

**Additional context**
Manual start:
sudo -u backup /home/backup/.local/bin/maestral start

**Comment by Access-deny** [comment] 2023-04-11 08:32
Filled in both manually with the replacement of the files so that both on the server and in the cloud are the same versions.
Maestral restored the previous versions of the files in the cloud, then renamed the files on the server to any_file.tar (conflicting copy).gz and downloaded the previous versions from the cloud to the server.
After updating the cache, the files on the server are not uploaded to the cloud, but the files from the cloud are uploaded to the server.
Maestral is a dangerous program that does not perform its declared functions, only harms.
You don't need to use it.
The idea is great, the execution is lousy.
Overall rating: 2 out of 100.

**Comment by Access-deny** [comment] 2023-04-12 07:18
I decided to wait and see what happens next.
Indeed, all NEW files that appear on the server and replace the old ones, maestral renames to tar (conflicting copy).gz, and downloads the version that is in the cloud.
Is this some kind of joke, @samschott?

**Comment by Access-deny** [comment] 2023-04-12 07:31
Running maestral on an Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz causes a very high load despite config (20). In logs 2023-04-11 20:04:23 sync DEBUG: maestral-download-pool_0: 163.6% CPU usage - throttling. 2023-04-11 20:04:23 sync DEBUG: maestral-download-pool_1: 163.0% CPU usage - throttling
And it crashes due to lack of memory (32 GB). Okay, there is oom-killer.
The most important thing is that maestral did not upload a single byte to the cloud. Is maestral meant to keep files in the cloud from being overwritten?

**Comment by samschott** [comment] 2023-04-12 17:52
The config values "upload" and "download" are not really documented at the moment because they can have unintended consequences around maintaining an index that is consistent with the cloud. All they do is literally disable the threads that upload or download files, respectively. That being said, they do work as intended for me in manual testing.

Could you try unlinking and setting up Maestral again without modifying those, preferably with a new local folder? If you're trying to use Maestral as a drop-in replacement for the previous client, this should work.

**Comment by samschott** [comment] 2023-05-16 19:54
Closing this for now since I think the root cause is a misunderstanding of how the (admittedly undocumented) upload-only and download-only configurations are supposed to work.

**Closed by samschott** 2023-05-16 19:54 UTC
Labels: bug
