### ISSUE TITLE
Maestral is not starting as a service on Mac OS X

### ISSUE THREAD

**Issue by josep11** [samschott/maestral#530] opened 2021-11-25 10:06 UTC
Not starting the GUI client, nor syncing on start up

**To Reproduce**

**Expected behaviour**

**System:**

 - Maestral version:  v1.5.1
 - Python version: Python 3.8.5
 - OS: 10.14
 - Desktop environment: [e.g. Gnome 3.32]
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by SamSchott** [comment] 2021-11-25 19:33
@josep11, are you seeing any error messages or macOS crash reports?

You can also try to run the app from the Terminal by running

`/Applications/Maestral.app/Contents/MacOS/Maestral`

This should hopefully display some useful information in the Terminal indicating what might be happening.

**Comment by agebhard** [comment] 2022-01-10 12:23
@samschott I'm not the original poster but I have the same issue. This is my Terminal output:

`% /Applications/Maestral.app/Contents/MacOS/Maestral
Contents/Resources/app_packages/toga_cocoa/app.py:115: DeprecationWarning: There is no current event loop
[Cocoa] Not implemented: ScrollContainer.set_on_scroll()

`

I'm on Maestral v. 1.5.2 on macOS Monterey 12.1; This is an M1 Pro machine. Hope this helps?

**Comment by samschott** [comment] 2022-01-11 11:17
@agebhard, those two warnings are absolutely fine. I assume that in your case, the GUI actually does run when started manually?

**Comment by agebhard** [comment] 2022-01-11 20:03
Hey @samschott, no, the GUI does NOT actually run for me.

**Comment by samschott** [comment] 2022-01-13 15:27
Oh, that's annoying. Did it ever launch successfully, for example to complete the setup dialog? And do you see a Dock icon bouncing at any point? Is it possible that it might be actually running, just without the menu bar icon showing up?

**Comment by agebhard** [comment] 2022-01-13 15:48
Yes, it did launch successfully while I was on macOS 12.0.1 (I think) for example, I was able set things up and sync initially. Not sure if the update to 12.1 then brought the change, I didn't pay close attention. But these days, while on 12.1, it's not properly launching anymore. 
The dock icon DOES bounce, and something appears to be running in the background because LittleSnitch network monitor shows activity. Placing a video file into one of my Dropbox folders triggers upload activity. So that's good. But obviously we do need some kind of UI e.g. to be able to figure out when it's safe to pack up a laptop to not interrupt an upload etc.

**Comment by samschott** [comment] 2022-01-13 16:58
Ok, so at least part of the launch process is working as intended. This might be a long shot but could you try the following?

1. In Activity Monitor, quit or force-quit all Maestral processes. There should be two, one for the GUI and one for the sync daemon.
2. Install the latest development build from [here](https://nightly.link/samschott/maestral-cocoa/suites/4926981065/artifacts/142290168).
3. Relaunch and check if this fixes things.

I've made a couple of changes to the app bundle in the latest release which might well fix things.

**Comment by agebhard** [comment] 2022-01-13 18:15
Hey Sam, thank you. Followed the steps, unfortunately, immediately upon launch of the dev build, it crashed with this output:

`Traceback (most recent call last):
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 43, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 14, in main
  File "Contents/Resources/app/maestral_cocoa/app.py", line 44, in <module>
  File "Contents/Resources/app/maestral_cocoa/private/widgets.py", line 17, in <module>
  File "Contents/Resources/app/maestral_cocoa/private/platform.py", line 25, in get_platform_factory
  File "Contents/Resources/app/maestral_cocoa/private/implementation/cocoa/factory.py", line 24, in <module>
ImportError: cannot import name 'NSBezelStyle' from 'toga_cocoa.libs' (/Applications/Maestral.app/Contents/Resources/app_packages/toga_cocoa/libs/__init__.pyc)`

**Comment by samschott** [comment] 2022-01-13 18:18
Oops, the link pointed to a previous build. Try this one [here](https://nightly.link/samschott/maestral-cocoa/suites/4927537227/artifacts/142322283). Sorry for the hassle!

**Comment by agebhard** [comment] 2022-01-13 19:12
No problem. :) 
This latest link does not crash, but it also doesn't launch a GUI or menu bar icon. Activity Monitor shows both processes running again.

**Comment by agebhard** [comment] 2022-01-13 19:13
lmk if you want to find any log files for you (pls. specify what you might need)

**Comment by samschott** [comment] 2022-01-13 20:22
The trouble is that the GUI itself does not write any logs, only the sync process does. However, the launch might be hanging because there is a communication issue between the processes. Did you ever install the command line interface when things where still working? If not, you can still do so by simply creating a symlink with:

```console
$ ln -s /Applications/Maestral.app/Contents/MacOS/maestral-cli /usr/local/bin/maestral
```

Once the CLI is installed, could you go through the following steps?

1. Stop both Maestral processes again.
2. Clear the previous logs with the command `maestral log clear`.
3. Set the log level to debug with `maestral log level DEBUG`.
4. Restart Maestral.
5. Check in another terminal window if the daemon is responding with `maestral status`.
6. Post the debug logs here. You can access them with `maestral log show -e`. There might be some confidential information in those logs such as file names or values of environment variables. Make sure that you redact any sensitive information before posting.

This should hopefully show if there is any issue with the sync daemon itself. If there isn't, debugging will be a bit more difficult.

**Comment by agebhard** [comment] 2022-01-13 21:15
Done. (Removed everything that may have been private -- if you need the actual values for local or remote cursor, I can provide them directly.)

`
2022-01-13 16:03:58 daemon INFO: Starting daemon
2022-01-13 16:03:58 daemon DEBUG: Environment:
{'HOME': '/Users/<username>',
 'LANG': 'en_US.UTF-8',
 'LC_CTYPE': 'UTF-8',
 'LOGNAME': '<username>',
 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little '
         'Snitch.app/Contents/Components',
 'PWD': '/Users/<username>',
 'PYTHONDONTWRITEBYTECODE': '1',
 'PYTHONOPTIMIZE': '2',
 'PYTHONPATH': '/Applications/Maestral.app/Contents/Resources/app:/Applications/Maestral.app/Contents/Resources/app_packages',
 'PYTHONUNBUFFERED': '1',
 'SHELL': '/bin/zsh',
 'SHLVL': '2',
 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.xxxxx/Listeners',
 'TERM': 'xterm-256color',
 'TERM_PROGRAM': 'Apple_Terminal',
 'TERM_PROGRAM_VERSION': '443',
 'TERM_SESSION_ID': '<someID>',
 'TMPDIR': '/var/folders/cq/xxxxx/T/',
 'USER': '<username>',
 'XPC_FLAGS': '0x0',
 'XPC_SERVICE_NAME': '0',
 '_': '/Applications/Maestral.app/Contents/MacOS/Maestral',
 '__CFBundleIdentifier': 'com.apple.Terminal',
 '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0'}
2022-01-13 16:03:58 daemon DEBUG: Acquired daemon lock: '/Users/<username>/Library/Application Support/maestral/maestral.lock'
2022-01-13 16:03:58 daemon DEBUG: Integrating with CFEventLoop
2022-01-13 16:03:58 daemon DEBUG: Socket path: '/Users/<username>/Library/Application Support/maestral/maestral.sock'
2022-01-13 16:03:58 daemon DEBUG: Creating Pyro daemon
2022-01-13 16:03:58 sync DEBUG: Could not load mignore rules: No such file or directory
2022-01-13 16:03:58 daemon DEBUG: Starting event loop
2022-01-13 16:03:58 oauth DEBUG: Using keyring: keyring.backends.macOS.Keyring (priority: 5)
2022-01-13 16:04:01 manager INFO: Connecting...
2022-01-13 16:04:11 manager INFO: Connected
2022-01-13 16:04:11 sync DEBUG: Could not load mignore rules: No such file or directory
2022-01-13 16:04:14 manager DEBUG: Checking path root...
2022-01-13 16:04:14 manager DEBUG: Path root is up to date
2022-01-13 16:04:14 sync INFO: Fetching remote changes
2022-01-13 16:04:14 sync DEBUG: Fetching remote changes since cursor: <codeRemoved>
2022-01-13 16:04:15 sync DEBUG: Remote changes:
[]
2022-01-13 16:04:15 sync DEBUG: Converted remote changes to SyncEvents
2022-01-13 16:04:15 sync DEBUG: Remote cursor saved: <codeRemoved>
2022-01-13 16:04:15 sync INFO: Indexing local changes...
2022-01-13 16:04:16 sync DEBUG: Local indexing completed in 1.0299 sec
2022-01-13 16:04:16 sync DEBUG: Retrieved local changes:
[]
2022-01-13 16:04:16 sync DEBUG: No local changes while inactive
2022-01-13 16:04:16 sync DEBUG: Local cursor saved: <codeRemoved>
2022-01-13 16:04:16 manager INFO: Up to date
2022-01-13 16:04:16 sync DEBUG: Waiting for local changes since cursor: <codeRemoved>
2022-01-13 16:04:16 sync DEBUG: Waiting for remote changes since cursor: <codeRemoved>
2022-01-13 16:04:56 sync DEBUG: Waiting for local changes since cursor: <codeRemoved>
2022-01-13 16:05:04 sync DEBUG: Detected remote changes: False
2022-01-13 16:05:04 manager DEBUG: Checking path root...
2022-01-13 16:05:05 manager DEBUG: Path root is up to date
2022-01-13 16:05:05 sync DEBUG: Waiting for remote changes since cursor: <codeRemoved>
2022-01-13 16:05:36 sync DEBUG: Waiting for local changes since cursor: <codeRemoved>
`

**Comment by agebhard** [comment] 2022-01-13 21:15
ugh. what happened to the formatting?

**Comment by samschott** [comment] 2022-01-13 21:30
No worries, I've fixed the formatting for you. The log looks perfectly fine, Maestral is definitely syncing as intended, just without a GUI.

I should be able to provide a debug build of the app bundle with log messages which show where exactly the GUI hangs in the startup process but I likely won't be able to do this until next week.

For reference, I suspect that issue #569 might be related to this.

**Comment by agebhard** [comment] 2022-01-13 21:34
Sounds good, thanks for walking me through this and for the timeline. And I agree after reading #569 that issue seems identical.

**Comment by samschott** [comment] 2022-01-14 18:28
Ok, I got to it a bit earlier than expected :) [Here](https://nightly.link/samschott/maestral-cocoa/suites/4941297084/artifacts/143069818) is the new build with debug output from the GUI. You will need to run it from the Terminal by running `/Applications/Maestral.app/Contents/MacOS/Maestral` to see the output printed there, it won't be in the log files. Could you report back what you see?

Another idea which is worth trying is to run Maestral with a fresh configuration to trigger the setup dialog:

```console
$ /Applications/Maestral.app/Contents/MacOS/Maestral --config-name new-config
```

This should launch into the setup dialog. Does the setup window open? And if it does, do you also see the menu bar icon? It should appear greyed out, since you are not yet linked, but it should still be there and present a menu with fewer options.

**Comment by agebhard** [comment] 2022-01-14 18:50
Terminal output is the following:

```
% /Applications/Maestral.app/Contents/MacOS/Maestral
Starting sync daemon
Instantiating autostostart and Sparkle updater
Setting up manu bar icon
Setting up unlinked UI
Checking linked status
Already linked
Starting sync
Setting up linked UI
[Cocoa] Not implemented: ScrollContainer.set_on_scroll()
Starting Sparkle update checker
Startup complete
^C [I waited 2 minutes before I hit control-C here...]
% 
```

No menu bar icon or UI ever appeared. Is the above output giving you a meaningful hint yet? (I'm asking because I'd like to avoid risking to kill and having to redo my configuration, just in case that UI doesn't come up...)

**Comment by samschott** [comment] 2022-01-14 18:54
The output suggests that startup runs through fine. The menu bar icon should become visible just after `Setting up menu bar icon`.

> I'd like to avoid risking to kill and having to redo my configuration

No worries, your configuration won't be lost. The "new-config" will be completely independent, for example if you'd want to sync a second Dropbox account. It will only every be used when specify the `--config-name new-config` in the CLI.

**Comment by agebhard** [comment] 2022-01-14 19:36
Gotcha. Ok, the Terminal output of running it with a new config name is this:

```
% /Applications/Maestral.app/Contents/MacOS/Maestral --config-name new-config1
Starting sync daemon
Instantiating autostostart and Sparkle updater
Setting up manu bar icon
Setting up unlinked UI
Checking linked status
Not yet linked, running setup dialog
% 
```

It does show the setup window (though now menu bar icon yet). I did not finish the setup process, though. (Hit the red icon to close the window instead.)

Instead, I clicked on the app icon again to see if maybe ("magically") the standard config would now start. It did not. But I did stream the console output before clicking the app icon and then looked through the results (filtered by the term "Maestral"). There was one line item that was marked as an error; this is the content of that:

`Prompting policy for hardened runtime; service: kTCCServiceAppleEvents requires entitlement com.apple.security.automation.apple-events but it is missing for accessing={<TCCDProcess: identifier=com.samschott.maestral, pid=75047, auid=501, euid=501, binary_path=/Applications/Maestral.app/Contents/MacOS/Maestral>}, requesting={<TCCDProcess: identifier=com.apple.appleeventsd, pid=490, auid=55, euid=55, binary_path=/System/Library/CoreServices/appleeventsd>}`

**Comment by agebhard** [comment] 2022-01-14 19:37
If you'd like the entire console output, lmk and I can email it to you directly...

**Comment by agebhard** [comment] 2022-01-14 19:40
Oh, I also found one other entry that suggests an error, right at the top:
`Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Applications/Maestral.app/Contents/, NSFilePath=/Applications/Maestral.app/Contents/PlugIns, NSUnderlyingError=0x14b724a60 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}`

**Comment by samschott** [comment] 2022-01-14 20:12
Thanks for the infos! The error messages in the Console app are all fine, Maestral does not currently request the apple events entitlement and does not have any plugins.

The fact that you do see the setup window but not the menu bar icon, as well as the debug output, all suggest that the GUI is indeed running. For some reason, it is just not showing the menu bar icon. Unfortunately, since the GUI really is *only* the menu bar icon and a couple of dialogs, this leaves it pretty much not functional :(

Could it be as simple as menu bar icons overflowing because there are too many? Or is it hidden behind the notch? At this point, I suspect it might be something with your settings or system configuration interfering.

**Comment by agebhard** [comment] 2022-01-14 21:10
@samschott f... me. Or effin notch. Either way, that's what it was: Once I grabbed what looked like the leftmost menu bar icon and command-moved it further left the Maestral icon moved into view. And all the commands trigger a window as expected. So this was a classic user error on my part and I apologize for your time I wasted. Thank you!

**Comment by samschott** [comment] 2022-01-14 21:24
@agebhard, glad its resolved! And you get to keep the debug build for free :)

On a more productive note, maybe the debug build will be helpful for @josep11, I expect that his original issue may have been a different one.

**Comment by josep11** [comment] 2022-01-18 11:08
> @agebhard, glad its resolved! And you get to keep the debug build for free :)
> 
> On a more productive note, maybe the debug build will be helpful for @josep11, I expect that his original issue may have been a different one.

Hello @samschott, mine got fixed some days after posting. Idk how, hehehe
If it surfaces again I'll keep you updated. Thanks

**Comment by samschott** [comment] 2022-02-12 20:22
Alright, in this case I'll close the issue. Feel free to reopen if it occurs again.

**Closed by samschott** 2022-02-12 20:22 UTC
Labels: bug
