### ISSUE TITLE
[BUG] After upgrading to v1.3.1 getting error "Cannot create temporary file (errno 1)

### ISSUE THREAD

**Issue by Mohammad-Asiri** [SamSchott/maestral#272] opened 2020-12-22 11:34 UTC
**Describe the bug**

After updating maestral from v1.2.1 to v1.3.1, on startup I get an Error notification that shows the following "Cannot create temporary file(errno 1)".
Also a message pops up that has the following "Cannot create temporary file (errno 1) \nPlease check if you have write permissions for /path/to/maestral/folder/.maestral.cache"

By the way, I am using the maestral[gui] install and update method.
 
I have shutdown maestral and deleted that folder, on starting up maestral, it will create that folder and starts populating it with files and then the same notification and message are shown again.

**To Reproduce**

It might a problem on my system only, but here goes.
Create your maestral drop box folder on an NTFS partition and then restart maestral.

**Expected behaviour**

maestral working without a hitch.

**System (please complete the following information):**
 - Maestral version: 1.3.1
 - OS: [e.g. Ubuntu] Linux Mint 20
 - Desktop environment: Cinnamon
 - Qt version: 5.12.8

**Additional context**

I have the maestral drop box folder on a NTFS files system, since I dual boot the PC.
When I was on version 1.2.1 the program was running perfectly, but after the upgrade this problem started happening.

**Comment by SamSchott** [comment] 2020-12-23 20:12
Hi @Mohammad-Asiri, the error is indeed a permission error. v1.3.1 did change the file permissions for downloaded files. From the changelog:

> Fixes an issue where all newly downloaded files would be created with 755 permissions. They are now created with the user's default permissions for new files instead.

This however should not cause any issues since we now attempt to create the cache files with the default user permissions. It certainly worked in the automatic tests which are run before every release.

A few steps to trouble shoot:
* Could you post the full traceback here? You can find it in the logs with `maestral log show`.
* Where is your Dropbox folder located? In your home folder or a more unusual location?
* Does the error occur for every download sync? Or can you successfully sync a few files before it shows up? To test, you can manually upload a file on the Dropbox website and see if it downloads correctly. If you do manage a number of successful downloads, this could indicate that another program is changing the permissions of the Dropbox folder.

Sorry for not being more specific, I am just trying to narrow down the possible cause.

**Comment by Mohammad-Asiri** [comment] 2020-12-27 05:59
> Hi @Mohammad-Asiri, the error is indeed a permission error. v1.3.0 changed the file permissions for downloaded files. From the changelog:
> 
> > Fixes an issue where all newly downloaded files would be created with 755 permissions. They are now created with the user's default permissions for new files instead.
> 
> This however should not cause any issues since we now attempt to create the cache files with the default user permissions. It certainly worked in the automatic tests which are run before every release.
> 
> A few steps to trouble shoot:
> 
>     * Could you post the full traceback here? You can find it in the logs with `maestral log show`.
> 
>     * Where is your Dropbox folder located? In your home folder or a more unusual location?
> 
>     * Does the error occur for every download sync? Or can you successfully sync a few files before it shows up? To test, you can manually upload a file on the Dropbox website and see if it downloads correctly. If you do manage a number of successful downloads, this could indicate that another program is changing the permissions of the Dropbox folder.
> 
> 
> Sorry for not being more specific, I am just trying to narrow down the possible cause.

Sorry for my late reply, I had to get back to the computer with maestral installed in it.

Thank you for the trouble shooting steps,
1. The log file is attached to this reply.
2. The Dropbox folder is located in an NTFS partition for easy access in both Windows and Linux.
3. The error happens at the start of maestral. I will get the notification and a pop up message, and then the maestral icon in the notification tray becomes a circle with an X inside it. I created a file in the local Dropbox folder and it does not sync with the cloud, and I created a file in the cloud but will not sync with my local Dropbox folder.

It seems that maestral continues to function as a program, but its syncing functionality stops. It will not sync any files.

[maestral.log](https://github.com/SamSchott/maestral/files/5744126/maestral.log)

**Comment by SamSchott** [comment] 2020-12-27 12:36
Ok, thanks for the log! It looks like the error does not occur when creating the temporary file but rather when changing its permissions.

Could you check and post the permissions for all of the following:

1. The local Dropbox folder.
2. The cache folder `.maestral.cache`.
3. Any temporary files created inside `.maestral.cache`, if they still exist.

**Comment by Mohammad-Asiri** [comment] 2020-12-28 10:03
> Ok, thanks for the log! It looks like the error does not occur when creating the temporary file but rather when changing its permissions.
> 
> Could you check and post the permissions for all of the following:
> 
>     1. The local Dropbox folder.
> 
>     2. The cache folder `.maestral.cache`.
> 
>     3. Any temporary files created inside `.maestral.cache`, if they still exist.
> 
> 
> Edit: Please also check the owner of the directories / files. You can get both permissions and owners with `ls -l`.

These are the Owner, Group, and permissions.

1. Local Dropbox folder: root root drwxrwxrwx
2. Folder .maestral.cache: root root drwxrwxrwx
3. temp files inside .maestral.cache folder: root root -rwxrwxrwx

I hope this information is helpful.

**Comment by SamSchott** [comment] 2020-12-28 11:06
Hm, those are very permissive. The only concern is that the directories are owned by root. Are you running Maestral as the root user? If not, it won't be able to modify the permissions of files inside the Dropbox folder. That would explain the error.

You can try to change the ownership with `chown $USER:$USER -R` where `$USER` is the account which you are using to run Maestral.

**Comment by SamSchott** [comment] 2020-12-28 12:33
Finally, you can also try to manually change permissions of any temporary file in the cache dir to 666 with `chmod 666 path/to/file`. This is effectively what the sync is trying to do programatically. Does this succeed?

**Comment by Mohammad-Asiri** [comment] 2021-01-04 08:21
> Finally, you can also try to manually change permissions of any temporary file in the cache dir to 666 with `chmod 666 path/to/file`. This is effectively what the sync is trying to do programatically. Does this succeed?

Hi Sam, after some trouble shooting, I found a solution to my problem.

Since I had my Dropbox folder in an exfat partition, I was not able to change the ownership of the folder to my user name.

So I edited my /etc/fstab file and added uid=1000 and gid=1000 to the exfat partition. You get something like this
`UUID-Your-Partition    /where/is/the/mount/point   exfat   defaults,uid=1000,gid=1000  0  2`

The uid and gid are my user name user id and group id numbers.

After rebooting my computer I got the proper owner and group for the Dropbox folder, but I still was not able to sync and the tray icon was showing X.

I went to maestral preferences, and changed the folder that holds the Dropbox folder to a partition that is EXT4, renamed the folder on the exfat partition, and then went to maestral preferences and choose the exfat folder that will hold the Dropbox folder and everything was working again.

I found out that the partition was an exfat and not NTFS.

I hope this will help others that are facing the same problem.

**Comment by SamSchott** [comment] 2021-01-04 22:02
Ah, this explains it! Thank you for the thorough writeup. Typically on Linux the user who created the file automatically becomes the owner and I was very confused by root owning the files while not being able to chmod. But exFAT and NTFS don't have Unix-type file permissions. I am not even sure if the chmod call has any effect there...

I am considering to only emit a warning instead of raising an error when setting the permissions fails. In any case, I'll close this for now since the error is indeed expected behaviour, despite being very obscure.

**Closed by SamSchott** 2021-01-04 22:02 UTC
