### ISSUE TITLE
Bad input to API Call error message

### ISSUE THREAD

**Issue by snowppl** [samschott/maestral#685] opened 2022-05-31 20:47 UTC
**Describe the bug**

Error Message:

Bad input to API Call
{"error": "v1_retired""

**To Reproduce**

Not sure. I updated Maestral to v1.6.2 and MacOS to 12.4

**Expected behaviour**

No error message

**System:**

 - Maestral version: v1.6.2
 - Python version: not sure
 - OS: [e.g. Ubuntu] MacOS 12.4
 - Desktop environment: [e.g. Gnome 3.32] MacOS 12.4?
 - PyQt version (for Linux GUI):

**Additional context**

**Comment by ncchandler42** [comment] 2022-05-31 20:58
Duplicate of #683

**Closed** 2022-05-31 21:11 UTC
Labels: bug
