### ISSUE TITLE
CLI Maestral activity crash missing libncursesw (MacOS 12.1)

### ISSUE THREAD

**Issue by janczawadzki** [samschott/maestral#589] opened 2022-01-26 04:06 UTC
In Terminal type **maestral activity**

Crash:

```
  File "Contents/Resources/app_packages/maestral/cli.py", line 1007, in activity
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/curses/__init__.py", line 13, in <module>
ImportError: dlopen(/Applications/Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.10/lib-dynload/_curses.cpython-310-darwin.so, 0x0002): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.10/lib/libncursesw.5.dylib
  Referenced from: /Applications/Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.10/lib-dynload/_curses.cpython-310-darwin.so
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/libncursesw.5.dylib' (no such file), '/usr/lib/libncursesw.5.dylib' (no such file)
```

**System:**
 - Maestral version: 1.5.2
 - Python version: 3.9
 - OS: MacOS 12.1

**Comment by samschott** [comment] 2022-01-26 19:42
Duplicate of #533. This will be fixed in the next release.

**Closed by samschott** 2022-01-26 19:42 UTC
Labels: bug
