### ISSUE TITLE
Cannot start maestral GUI: maestral_profile_pic.jpeg not found

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#515] opened 2021-11-06 09:53 UTC
**Describe the bug**

I have upgraded from Fedora 34 Workstation to Fedora 35 Workstation.

I had to reinstall maestral: `pip3 install --ugprade maestral[gui]`

Now the GUI won't start:
```
$ maestral gui
QSocketNotifier: Can only be used with threads started with QThread
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
QImage::pixel: coordinate (0,0) out of range
Traceback (most recent call last):
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 186, in set_profile_pic_from_cache
    pixmap = get_masked_image(
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/utils.py", line 181, in get_masked_image
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/raffaele/.cache/maestral/maestral_profile_pic.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raffaele/.local/bin/maestral", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral/cli.py", line 711, in gui
    run(config_name)
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 631, in run
    maestral_gui.load_maestral()
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 197, in load_maestral
    self.setup_ui_linked()
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/main.py", line 254, in setup_ui_linked
    self.settings_window = SettingsWindow(self, self.mdbx)
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 117, in __init__
    self.refresh_gui()
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 153, in refresh_gui
    self.set_profile_pic_from_cache()
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/settings_window.py", line 190, in set_profile_pic_from_cache
    pixmap = get_masked_image(FACEHOLDER_PATH, size=self._profile_pic_height)
  File "/home/raffaele/.local/lib/python3.10/site-packages/maestral_qt/utils.py", line 192, in get_masked_image
    rect = QRect(
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'
```

**To Reproduce**
See above

**Expected behaviour**
The GUI should start

**System:**

 - Maestral version: 1.5.1
 - Python version: 3.10
 - OS: Fedora 35 Workstation
 - Desktop environment: GNOME 41
 - PyQt version (for Linux GUI): 5.15.0

**Comment by SamSchott** [comment] 2021-11-06 11:35
Duplicate of #509.

**Closed by SamSchott** 2021-11-06 11:35 UTC
Labels: bug
