### ISSUE TITLE
maestral activity crashes app on MacOS

### ISSUE THREAD

**Issue by riesentoaster** [samschott/maestral#591] opened 2022-01-26 15:50 UTC
**Describe the bug**
When running `maestral activity` in the Terminal, the app crashes (Traceback see below).

**To Reproduce**
Run `maestral activity`.

Does not depend on whether the app (GUI) is running or not.

**Expected behaviour**
Not crashing (I don't actually know what is supposed to happen, I was just poking at the CLI to get to know it).

**System:**
 - Maestral version: 1.5.2 (both deamon and GUI)
 - Python version: 3.9.10 (or at least that's what `python3 --version` outputs. Don't know if maestral uses this as opposed to other installations)
 - OS: MacOS 12.1 (Monterey) on M1 Pro

**Additional context**
```
Traceback (most recent call last):
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 86, in _run_code
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 41, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 36, in freeze_support_cli
  File "Contents/Resources/app_packages/click/core.py", line 1128, in __call__
  File "Contents/Resources/app_packages/click/core.py", line 1053, in main
  File "Contents/Resources/app_packages/click/core.py", line 1659, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 1395, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 754, in invoke
  File "Contents/Resources/app_packages/maestral/cli.py", line 227, in wrapper
  File "Contents/Resources/app_packages/maestral/cli.py", line 1007, in activity
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/curses/__init__.py", line 13, in <module>
ImportError: dlopen(/Applications/Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.10/lib-dynload/_curses.cpython-310-darwin.so, 0x0002): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.10/lib/libncursesw.5.dylib
  Referenced from: /Applications/Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.10/lib-dynload/_curses.cpython-310-darwin.so
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/libncursesw.5.dylib' (no such file), '/usr/lib/libncursesw.5.dylib' (no such file)
```

**Comment by riesentoaster** [comment] 2022-01-26 15:51
Oh, this seems to be a duplicate for #589 and #533. Feel free to close this if no longer needed.

**Comment by samschott** [comment] 2022-01-26 19:41
Indeed, a duplicate of #533. Will be fixed in the next release.

**Closed by samschott** 2022-01-26 19:41 UTC
Labels: bug
