### ISSUE TITLE
Command-line tools won't install from bundle

### ISSUE THREAD

**Issue by mattriffle** [SamSchott/maestral#358] opened 2021-03-18 14:25 UTC
Hi, let me first say thanks for a great tool.  It is so much better than having to run the official Dropbox bloated client.

I'm on an M1 MacBook Pro and Big Sur 11.2.3 (not sure if either of those will be relevant).  I'm running the latest pre-packaged 1.4.3 version, installed from the DMG.

When I click the button to install the command-line tools, nothing happens.  No errors, no dialogs, and also no tools.

I notice the text underneath the button notes they'll be installed to /usr/local/bin -- I don't actually have a /usr/local/bin directory -- /usr/local is empty.  I tried making a /usr/local/bin and ensuring I had permissions to write to it, but, that didn't do anything, either.

I'm happy to do any debugging that would be useful.

**Comment by SamSchott** [comment] 2021-03-18 17:49
@mattriffle, thanks for the report. I suspect that this is indeed related to running on Apple Silicon and tightened security there. Running macOS Big Sur on an Intel Mac, I get the expected prompt for a password when installing the CLI.

Could you try launching the app from the Terminal by running `/Applications/Maestral.app/Contents/MacOS/Maestral` and repeat the same steps? Hopefully this will print a useful error message to the terminal.

**Comment by mattriffle** [comment] 2021-03-18 18:21
Okay, I've experimented a little, and this is what I've found.  On start up, we always get this one warning:

matt@Matthews-MacBook-Pro Downloads % /Applications/Maestral.app/Contents/MacOS/Maestral
[Cocoa] Not implemented: ScrollContainer.set_on_scroll()

If I let Maestral run, no other warnings or errors pop up.  I can open the preferences window and do some non-CLI things, like change the frequency of checking for updates, and looking at the folders I've selected for Selective Sync.  I can do other things from the menu bar, like looking at sync issues and actually checking for an update.  No errors.  Now, finally I try the CLI install and I get this:

2021-03-18 14:16:09.436 Maestral[20725:1575780] -[__NSCFNumber length]: unrecognized selector sent to instance 0xbdfcc9ec389956ee
Exception ignored on calling ctypes callback function: <function CFTimerHandle._cf_timer_callback.<locals>.cf_timer_callback at 0x1264c4a60>
Traceback (most recent call last):
  File "Contents/Resources/app_packages/rubicon/objc/eventloop.py", line 155, in cf_timer_callback
  File "Contents/Resources/app_packages/rubicon/objc/eventloop.py", line 304, in _callback
RuntimeError: Cannot enter into task <Task pending name='Task-37' coro=<SettingsWindow.periodic_refresh_gui() running at Contents/Resources/app/maestral_cocoa/settings.py:199> wait_for=<Future finished result=None>> while another task <Task pending name='Task-38' coro=<handler_with_cleanup() running at Contents/Resources/app_packages/toga/handlers.py:25>> is being executed.
Exception ignored on calling ctypes callback function: <function CFTimerHandle._cf_timer_callback.<locals>.cf_timer_callback at 0x1264c4e50>
Traceback (most recent call last):
  File "Contents/Resources/app_packages/rubicon/objc/eventloop.py", line 155, in cf_timer_callback
  File "Contents/Resources/app_packages/rubicon/objc/eventloop.py", line 304, in _callback
RuntimeError: Cannot enter into task <Task pending name='Task-3' coro=<SettingsWindow.periodic_refresh_gui() running at Contents/Resources/app/maestral_cocoa/settings.py:199> wait_for=<Future finished result=None>> while another task <Task pending name='Task-38' coro=<handler_with_cleanup() running at Contents/Resources/app_packages/toga/handlers.py:25>> is being executed.

Once that has happened, just about everything starts throwing the same error, I presume because the task blocking things is still stuck.  If I kill and restart it's the same cycle.  So, not sure how useful that is, other than to say *something* seems to be hanging?  I'm happy to help with further debugging.

**Comment by SamSchott** [comment] 2021-03-18 19:09
Ah, that looks like a more serious error. I have a suspicion that the error is related to the privilege elevation code but I'm not quite sure, especially since you said that you *do* have write permissions to /usr/local/bin.

I have attached an App Bundle with uses hopefully more robust code for privilege elevation. Could you give this a try and see if the error persists?

[Maestral.app.zip](https://github.com/SamSchott/maestral/files/6166649/Maestral.app.zip)

**Comment by SamSchott** [comment] 2021-03-18 19:13
Otherwise, I have no real means to debug this since I'm running on an Intel Mac. The message which you have observed is helpful but it appears to be a symptom of a different unreported error rather than the actual cause.

If you'd like to run the CLI in meantime, you can manually create a symlink in `/usr/local/bin` to `/Applications/Maestral.app/Contents/MacOS/maestral-cli`.

**Comment by mattriffle** [comment] 2021-03-18 20:41
Got pretty much the same error.  I'll just make the symlink for now -- if it's not working in some other way, I haven't noticed.  It's syncing files fine, as far as I've noticed.  Thanks.

**Comment by SamSchott** [comment] 2021-03-19 00:53
I was hoping this would fix things because it removes the usage of some deprecated APIs for elevated privileges. But maybe they were not problematic in the first place.

The sync daemon makes much less use of macOS specific APIs and therefore should have a smoother experience on a M1 Mac. In general, I’ll be curious to hear about your experience on Apple Silicon since this is something which I cannot test at all. So please do report if anything else seems off.

On that note, you could try one more thing to see if this really is a M1 problem: force the app to run under Rosetta translation (right-click > Get Info > Open using Rosetta). If the problem persists, it might be able to reproduce this on my end.

**Comment by hstriepe** [comment] 2021-04-18 15:17
It worked fine on my M1 under 12.3beta. But I already have a configured /usr/local/bin for Intel Brew (aliased as ibrew) and other commands. BTW, native Homebrew on M1 is now in /opt/homebrew.

**Comment by tconroy** [comment] 2021-11-20 19:41
Also encountering this issue on a M1 MacBook, fresh install.

- when I click `Maestral.app`, the GUI never opens.
- I see the process in activity monitor
- if I try to run GUI from the CLI I see this error, and the GUI does not open:
```
❯ maestral gui
[Cocoa] Not implemented: ScrollContainer.set_on_scroll()
```

**Comment by SamSchott** [comment] 2021-11-23 17:08
@tconroy, I suspect you are seeing a different issue. For you, the GUI does not show up at all in the first place.

**Comment by SamSchott** [comment] 2021-11-23 17:13
I finally got my hands on an M1 Mac Mini for some testing this week and could reproduce the issue. It should be fixed in the linked commit. A new release with the fix will follow shortly. For now, please manually symlink

`/usr/local/bin` -> `/Applications/Maestral.app/Contents/MacOS/maestral-cli`

to install the CLI in your PATH.

**Closed** 2021-11-23 17:13 UTC
Labels: gui, macOS
