### ISSUE TITLE
[BUG] AttributeError: remote object 'PYRO:maestral.maestral@./u:/run/user/1000/maestral/maestral.sock' has no exposed attribute or method 'analytics'

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#291] opened 2021-01-26 15:15 UTC
**Describe the bug**

I am on commit `e3cc6ffac529b1c61ba9d31d01e3333bc0d0b963` (latest one)

After `python3 setup.py install`, running `maestral gui` returns this:

```
$ maestral gui
Gtk-Message: 16:10:35.739: Failed to load module "appmenu-gtk-module"
Traceback (most recent call last):
  File "/usr/local/bin/maestral", line 33, in <module>
    sys.exit(load_entry_point('maestral==1.3.2.dev0', 'console_scripts', 'maestral')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/maestral-1.3.2.dev0-py3.8.egg/maestral/cli.py", line 665, in gui
    run(config_name)
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 638, in run
    maestral_gui.load_maestral()
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 190, in load_maestral
    self.setup_ui_linked()
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/main.py", line 247, in setup_ui_linked
    self.settings_window = SettingsWindow(self, self.mdbx)
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/settings_window.py", line 116, in __init__
    self.refresh_gui()
  File "/home/raffaele/.local/lib/python3.8/site-packages/maestral_qt/settings_window.py", line 172, in refresh_gui
    self.checkBoxAnalytics.setChecked(self.mdbx.analytics)
  File "/usr/local/lib/python3.8/dist-packages/maestral-1.3.2.dev0-py3.8.egg/maestral/daemon.py", line 755, in __getattr__
    return self._m.__getattr__(item)
  File "/home/raffaele/.local/lib/python3.8/site-packages/Pyro5/client.py", line 97, in __getattr__
    raise AttributeError("remote object '%s' has no exposed attribute or method '%s'" % (self._pyroUri, name))
AttributeError: remote object 'PYRO:maestral.maestral@./u:/run/user/1000/maestral/maestral.sock' has no exposed attribute or method 'analytics'
```

**Comment by SamSchott** [comment] 2021-01-26 19:11
Oh, that is courageous! Analytics / automatic crash reporting has been removed in the development branch. But it looks like your version of the GUI does not know about it.

Can you also update the GUI to the latest commit from https://github.com/SamSchott/maestral-qt?

**Comment by SamSchott** [comment] 2021-01-26 19:20
I'm closing this since a) it's not a bug and b) it's for the development branch.

**Closed by SamSchott** 2021-01-26 19:20 UTC
