### ISSUE TITLE
Error message 'File A' and 'File A' are the same file

### ISSUE THREAD

**Issue by jonathanlang** [samschott/maestral#878] opened 2023-04-16 17:31 UTC
**Describe the bug**
I'm getting this error message during sync (redacted filenames for privacy reasons, but have double-checked that the file path is identical): 
'/Users/jon/Dropbox/Dokumente/foo/bar.pdf' and '/Users/jon/Dropbox/Dokumente/foo/bar.pdf' are the same file.

This keeps popping up during syncing. Updating to 1.7.1 did not fix it. The files have not been touched recently. 

**To Reproduce**
Start Maestral macOS GUI client. Wait for syncing to happen. During sync, it throws the error on occasion. 

**Expected behaviour**
This shouldn't be an error, since the statement is true... they are the same file, and I'm not sure why it's trying to do anything with it. 

**System:**

 - Maestral version: 1.7.1
 - Python version: Python 3.9.6
 - OS: macOS Ventura 13.3.1
 - Desktop environment:
 - PyQt version (for Linux GUI):

**Additional context**
I've been using the Maestral client for probably a year now and haven't encountered this bug before.

**Comment by samschott** [comment] 2023-04-16 18:05
That's indeed a true statement :) Could you check in the logs for a full traceback? I suspect an issue where Maestral tries to move a file from one path to another, with both paths being in fact equal (e.g., maybe different in casing only, which is equal as far as macOS is concerned). But it's hard to tell without knowing at what point the error was thrown.

**Comment by jonathanlang** [comment] 2023-04-16 18:15
Here's the excerpt from logs (filenames again redacted): 

> 2023-04-16 19:13:47 sync INFO: Syncing ↑ 10/77
> 2023-04-16 19:14:13 manager ERROR: Could not sync file or folder
> Traceback (most recent call last):
>   File "support/python-stdlib/shutil.py", line 824, in move
> PermissionError: [Errno 13] Permission denied: '/Users/jon/Dropbox/Dokumente/XXX/YYY.pdf' -> '/Users/jon/Dropbox/Dokumente/XXX/YYY.pdf'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "app_packages/maestral/errorhandling.py", line 90, in convert_api_errors
>   File "app_packages/maestral/sync.py", line 2606, in _handle_upload_conflict
>   File "app_packages/maestral/utils/path.py", line 383, in move
>   File "app_packages/maestral/utils/path.py", line 368, in move
>   File "support/python-stdlib/shutil.py", line 844, in move
>   File "support/python-stdlib/shutil.py", line 436, in copy2
>   File "support/python-stdlib/shutil.py", line 236, in copyfile
> shutil.SameFileError: '/Users/jon/Dropbox/Dokumente/XXX/YYY.pdf' and '/Users/jon/Dropbox/Dokumente/XXX/YYY.pdf' are the same file
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "app_packages/maestral/manager.py", line 797, in _handle_sync_thread_errors
>   File "app_packages/maestral/manager.py", line 783, in startup_worker
>   File "app_packages/maestral/sync.py", line 1545, in upload_local_changes_while_inactive
>   File "app_packages/maestral/sync.py", line 1784, in apply_local_changes
>   File "app_packages/maestral/sync.py", line 3723, in do_parallel
>   File "support/python-stdlib/concurrent/futures/_base.py", line 449, in result
>   File "support/python-stdlib/concurrent/futures/_base.py", line 401, in __get_result
>   File "support/python-stdlib/concurrent/futures/thread.py", line 58, in run
>   File "app_packages/maestral/sync.py", line 2127, in _create_remote_entry
>   File "app_packages/maestral/sync.py", line 2326, in _on_local_file_created
>   File "app_packages/maestral/sync.py", line 2605, in _handle_upload_conflict
>   File "support/python-stdlib/contextlib.py", line 155, in __exit__
>   File "app_packages/maestral/errorhandling.py", line 107, in convert_api_errors
> maestral.exceptions.MaestralApiError: Could not sync file or folder. '/Users/jon/Dropbox/Dokumente/XXX/YYY.pdf' and '/Users/jon/Dropbox/Dokumente/XXX/YYY.pdf' are the same file
> 2023-04-16 19:14:13 manager INFO: Shutting down threads...
> 2023-04-16 19:14:13 sync INFO: Sync aborted
> 2023-04-16 19:14:13 manager INFO: Paused
>

**Comment by samschott** [comment] 2023-04-16 19:22
Thanks! From that traceback, it looks like Dropbox saves the file on the server using a different file name, and Maestral tries to reproduce this locally by moving the local file. This fails because macOS perceives the old and the new paths to be the same.

Does the file name contain any special characters, e.g., with accents? If yes, which characters are those? Some special charters will be converted by Dropbox automatically to a different unicode representation. While technically a different path, macOS will still treat it as the same, it will look similar when printed to a log file. Maestral should be able to handle such file name normalisation transparently, but this appears to fail here.

**Comment by jonathanlang** [comment] 2023-04-17 11:39
They do indeed. There is an "ä" and a "-" in the filename.

**Comment by samschott** [comment] 2023-04-17 21:58
Ok, I've had a closer look at this:

1. The regular code path for Maestral would indeed be to rename the file, mirroring the changed name on Dropbox server:
   ```
   Decoded: ä -> ä
   Encoded: a\xcc\x88il -> \xc3\xa4
   ```
    It will do this, regardless of the local file system or OS.
2. This rename typically silently succeeds on macOS without actually doing anything. However, in your case, the rename fails with a PermissionError, resulting in Python trying to fall back to coping file and delete the old version instead. This copy operation however *does not* succeed either, because there is already a file at the old location.

So, the root cause really seems to be a permission error which is not reported properly, in combination with a rename that really was not required for macOS.

Could you check what the permissions are for the affected file?

**Comment by jonathanlang** [comment] 2023-04-20 18:40
Redacted filenames, here's the Terminal output: 

```
ls -lhart
total 1824
-rw-r--r--@  1 jon  staff   515K 22 Feb  2021 File A.pdf
-rw-r--r--@  1 jon  staff   396K 19 Jul  2022 File B.pdf
drwxr-xr-x  65 jon  staff   2,0K 30 Mär 01:10 ..
drwxr-xr-x   4 jon  staff   128B 16 Apr 19:13 .
```

**Comment by samschott** [comment] 2023-04-23 13:57
On a first glance, the permissions for the files themselves look fine to me. However, I just remember that to rename a file, you need to have write permissions for the parent folder as well. Could you also check that?

**Comment by jonathanlang** [comment] 2023-04-23 20:50
The last two lines in the excerpt above are the permissions for the folder and the parent folder I believe...

**Comment by samschott** [comment] 2023-04-23 21:12
Indeed, they are 🤦 In this case, I am somewhat out of ideas. The root error in the traceback that you posted is definitely a permission error which should not be occurring.

Two questions which might provide a hint:

1. I assume you are running Maestral as 'jon'?
2. Can you rename the file manually without needing to enter an admin password? If yes, does it sync successfully after renaming?

**Comment by jonathanlang** [comment] 2023-04-23 21:22
1) correct, it's running in my user context: 
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1255480/233866725-d756ff01-77d6-467e-a952-64575bcb1e8d.png">
2) When I try to rename the file, I am indeed prompted to enter my admin password / TouchID. Not sure why, since my user definitely has read-write rights: 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/1255480/233866934-7ddb356b-911b-4756-a1b3-745324596cb8.png">

**Comment by samschott** [comment] 2023-04-23 21:35
So some permission or ACL setting is indeed preventing a rename.

Is this for the file itself or the parent folder? Renaming will be controlled by the parent's permissions. And what does `ls -led PARENT_FOLDER` return? In particular, the `-e` flag will show macOS ACLs if present, in addition to Unix permissions.

**Comment by jonathanlang** [comment] 2023-05-01 11:49
Here's the output of ls -led in the folder. 
```
ls -led                            
drwxr-xr-x  4 jon  staff  128 16 Apr 19:13 .
```

**Comment by samschott** [comment] 2023-05-16 19:51
Sorry for the delay in coming back to this. From the output, there don't seem to be any custom ACLs set up for the immediate parent folder either, so I'm at a bit of a loss here. Maybe walking up the directory chain and checking if there are any custom ACLs there will help? Another way to debug this would also be to check if you can rename other files in the same chain of parent directories.

The latest release of Maestral should at least properly report a `PermissionError` in your case, instead of an enigmatic `SameFileError`. It is therefore working as intended, as far as sync capability is concerned, and I'll close this issue for now.

**Closed by samschott** 2023-05-16 19:51 UTC
Labels: bug
