### ISSUE TITLE
[BUG] Maestral deleted almost everything in my Dropbox

### ISSUE THREAD

**Issue by fabiansvara** [samschott/maestral#295] opened 2021-01-30 13:41 UTC
**Describe the bug**

After a fresh install of maestral on a system using the GPFS filesystem, almost the entire contents of my Dropbox were deleted upstream.

**To Reproduce**

I will provide a detailed description of what happened below, but I do not want to try to reproduce this.

**System (please complete the following information):**
 - Maestral version: maestral 1.3.1 from pip
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Desktop environment: None, CLI only

**Additional context**

I have used maestral on GPFS in the past a lot already. I am aware that this is an unsupported filesystem, but since I only care about upstream --> local sync, this should not matter for my usecase. It has, so far, always worked great for me.

This time, I did a fresh install of maestral (2 official Dropbox clients and 2 maestral clients are already running for the same Dropbox on other machines) on a new machine using the GPFS filesystem.

I have a largeish Dropbox (several 10k files, ~100GB stored), so I go do something else while it syncs up.

I come back to maestral seemingly having completed syncing, and very high activity on my official desktop client (different machine, obviously). I assume that due to filesystem limitations something is off about the file ctimes, and that it's going to realize there isn't anything to do. So again I go do something else.

I check back to find my Dropbox on my local machine empty, save a few dozen files. It looks like those files are mostly (but not exclusively) files that I looked at on the machine that had the new maestral installed.

The maestral directory of the newly installed client is still full, though, and looks (have no way of checking exactly) like it's complete. My other Dropbox clients and maestral installs have also deleted almost everything (and that's what the dropbox website shows too).

At that point, I stop the new maestral, make a backup copy of the maestral directory, and restart maestral. Maestral starts uploading files, and my other dropbox clients receive most of the original contents of my Dropbox again.

I let that run over night. The next day, all my official dropbox and maestral clients look like they have the full original contents again (again, no way of checking precisely). I restart the new maestral to make sure that it's stable now. It starts deleting files again.

This is where I give up, I'll restore my Dropbox contents from the backup copy I made earlier, though that's somewhat unsatisfactory since I can't check that against the contents of my Dropbox before this all started (N.b.: Dropbox' "rewind" feature seems to be half broken.) and sync back up with the official client...

**Comment by SamSchott** [comment] 2021-01-30 15:38
@fabiansvara, thank you for the detailed report. I am very sorry that this happened!

> The maestral directory of the newly installed client is still full, though, and looks (have no way of checking exactly) like it's complete. 

This is really confusing. There are two ways that local files get flagged as deleted and trigger a deletion on Dropbox servers:

1. The file system observer receives a "deleted" event from inotify. I am almost certain that this shouldn't happen with GPFS at all since inotify will likely be disabled for such a distributed file system. Or is it possibly enabled?

2. On startup or after the initial indexing and download, maestral will scan the entire directory and stat every file. It will then compare this directory snapshot against its database and emit "deleted" events for every entry in the database which is missing from the snapshot, "created" events for every entry in the snapshot which is missing from the database, and "modified" events depending on the ctimes vs sync times. If this directory snapshot for some reason is missing files which are actually in the file system, it will go ahead and remove them from Dropbox.

The second scenario seems more likely to me from your description. Deletions seems to be triggered either on startup or after the initial download. But I struggle to understand what might be going wrong. The directory snapshot really is only a succession of `os.scandir` and `os.stat` calls. Could this somehow fail on GPFS? And why would it only fail on one system?

Do you have log output from the times where it started deleting files? Could you share that? You can open the log in a text editor with `maestral log show -e`.

**Comment by fabiansvara** [comment] 2021-01-30 16:58
This is `~/.cache/maestral/maestral.log`

[maestral_log.txt](https://github.com/SamSchott/maestral/files/5898341/maestral_log.txt)

**Comment by SamSchott** [comment] 2021-01-30 17:52
Thanks! This really looks like the files are deleted during the "Indexing local changes" stage.

Are you comfortable with Python? If yes, could you try to run the following with the misbehaving instance?

1. Manually query for local changes:

   ```Python
   from pprint import pprint
   from maestral.main import Maestral

   m = Maestral()
   changes = m.sync._get_local_changes_while_inactive()
   pprint(changes)
   ```

    The above code won't sync anything but just report the detected changes. Does the output contain multiple `FileDeletedEvent`s? If yes, do some of those correspond to still existing files?

2. If this is the case, could you try to manually create a snapshot of the directory and see if those files are not showing up?
    ```Python
    from maestral.sync import DirectorySnapshot

    snapshot = DirectorySnapshot(m.dropbox_path)
    print(missing_path in snapshot.path)
    ```

3. Can you try to stat one of the missing paths? And scan its parent directory?

    ```Python
    import os

    os.stat(missing_path)
    list(os.scandir(os.dirname(missing_path)))
    ```
   Do those calls raise any errors?

**Comment by fabiansvara** [comment] 2021-01-30 19:22
I ran this:

>    ```python
>    from pprint import pprint
>    from maestral.main import Maestral
>    
>    m = Maestral()
>    changes = m.sync._get_local_changes_while_inactive()
>    ```

... followed by:
```python
In : len(changes[0])
Out: 17623
In : from pathlib import Path
In : all([Path(xx.src_path).exists() for xx in changes[0]])
Out: True
```

Here, I wasn't sure what missing_path was supposed to be:

>    ```python
>    from maestral.sync import DirectorySnapshot
>    
>    snapshot = DirectorySnapshot(m.dropbox_path)
>    print(missing_path in snapshot.path)
>    ```

... but I guess you wanted it to be one of the apparently deleted files. Also, `missing path in snapshot.path` raises

```python
TypeError: argument of type 'method' is not iterable
```

so I did:

```python
In : missing_path=changes[0][0].src_path
 
In : missing_path in snapshot.path.__repr__()
Out: True
```

Then, I ran

```python
In : import os
   : os.stat(missing_path)
Out: os.stat_result(st_mode=33188, st_ino=68673376, st_dev=43, st_nlink=1, st_uid=33815, st_gid=13600, st_size=1521350, st_atime=1611934115, st_mtime=1528900647, st_ctime=1611934115)
In : len(list(os.scandir(os.path.dirname(missing_path))))
Out: 136
```

>    Do those calls raise any errors?

```python
from pprint import pprint
from maestral.main import Maestral

m = Maestral()
```

raised

```
Could not connect to DBUS interface
Traceback (most recent call last):
  File "/home/folder/anaconda3/lib/python3.8/site-packages/maestral/notify/notify_linux.py", line 57, in _init_dbus
    self.bus = await MessageBus().connect()
  File "/home/folder/anaconda3/lib/python3.8/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/home/folder/anaconda3/lib/python3.8/site-packages/dbus_next/message_bus.py", line 73, in __init__
    get_bus_address(bus_type))
  File "/home/folder/anaconda3/lib/python3.8/site-packages/dbus_next/_private/address.py", line 98, in get_bus_address
    return get_session_bus_address()
  File "/home/folder/anaconda3/lib/python3.8/site-packages/dbus_next/_private/address.py", line 72, in get_session_bus_address
    with open('/var/lib/dbus/machine-id') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/dbus/machine-id'
```

**Comment by SamSchott** [comment] 2021-01-30 19:42
Thanks! This is still a bit confusing but we'll eventually get to the bottom of the issue.

Just to confirm the events listed in `changes[0]`, are those mostly `FileDeletedEvent`s and `DirDeletedEvent`s?

> Here, I wasn't sure what missing_path was supposed to be

Yeah, that was ambiguous. `missing_path` is supposed to be the path of an item which is listed as deleted in the list of changes but actually still exists. For instance:

```Python
# get changes
changes, timestamp = m.sync._get_local_changes_while_inactive()
# filter all deleted paths
deleted_paths = [event.src_path for event in changes if event.event_type == 'deleted']
# filter all paths incorrectly reported as deleted
incorrect_paths = [p for p in deleted_paths if os.path.exists(p)]
```

>  Also, missing_path in snapshot.path raises `TypeError: argument of type 'method' is not iterable`

Sorry, that was a typo. I meant: `missing_path in snapshot.paths`. For instance:

```Python
for path in incorrect_paths:
    if path in snapshot.paths:
        print(f'{path} was reported as deleted but exists in directory snapshot')
```

**Comment by SamSchott** [comment] 2021-01-30 19:47
The error message "Could not connect to DBUS interface" is safe to ignore, it just means that Maestral could not connect to a dbus service for desktop notifications (probably because you are on a headless system?).

**Comment by fabiansvara** [comment] 2021-01-30 20:17
> Thanks! This is still a bit confusing but we'll eventually get to the bottom of the issue.
> 
> Just to confirm the events listed in `changes[0]`, are those mostly `FileDeletedEvent`s and `DirDeletedEvent`s?
No, not most of them:

```python
In : from collections import Counter
In : Counter(type(xx) for xx in changes[0])
Out:
Counter({watchdog.events.FileCreatedEvent: 13476,
         watchdog.events.DirCreatedEvent: 1879,
         watchdog.events.DirDeletedEvent: 1037,
         watchdog.events.FileDeletedEvent: 1231})
```

> > Here, I wasn't sure what missing_path was supposed to be
> 
> Yeah, that was ambiguous. `missing_path` is supposed to be the path of an item which is listed as deleted in the list of changes but actually still exists.

Ok, but that's what I thought you meant and at least item 0 was listed as deleted, existed on disk, and was also in the snapshot.

Anyhow I ran all of this ...

> ```python
> # get changes
> changes, timestamp = m.sync._get_local_changes_while_inactive()
> # filter all deleted paths
> deleted_paths = [event.src_path for event in changes if event.event_type == 'deleted']
> # filter all paths incorrectly reported as deleted
> incorrect_paths = [p for p in deleted_paths if os.path.exists(p)]
>
> for path in incorrect_paths:
>     if path in snapshot.paths:
>         print(f'{path} was reported as deleted but exists in directory snapshot')
> ```

and it prints lots of files. In fact, all of the "deleted" ones.

```python
In : count = 0
...: for path in incorrect_paths:
...:     if path in snapshot.paths:
...:         count += 1
In : print(count)
2268

In : len(deleted)
Out: 2268
```

**Comment by SamSchott** [comment] 2021-01-31 01:04
This is all very strange. It looks like some files are picked up by the manual directory snapshot but not by the one created during `_get_local_changes_while_inactive`. Also, the number of reported deletions is actually quite a bit smaller than I expected from your previous reports. But the total number of reported changes seems very large (13476 unindexed files?).

Are there any other entries for the same paths reported in the change set? For example, if a file has been replaced by a folder, there will be two events (FileDeletedEvent and DirCreatedEvent) for the same path. This could explain some of the deleted events. Also, are any of the events in the list of changes unexpected, apart from the deleted events?

Apart from this, I really have no clue as to what might be happening. If the file names are not confidential, you could possiblly pickle the directory snapshot and the list of changes and send them to me together with the index file at `~/.local/share/maestral/maestral.db`. Maybe this will help to understand those phantom deletions (and creations?) are coming from.

**Comment by SamSchott** [comment] 2021-01-31 01:07
Finally, you try excluding all folders but a single test folder from sync and see if you can reproduce the behaviour with a more controlled number of files.

Also, thanks for bearing with me. I am really sorry for all the trouble! Mostly, I am concerned that the deletions are not a consequence of an unsupported file system but come from another error. So it would be good to understand what happened.

**Comment by fabiansvara** [comment] 2021-01-31 12:55
Before I try these things, I think I know what must have happened: Does maestral keep a cache of Dropbox contents around that persists between installs? I just remembered I had maestral installed on this machine already ~2 years ago, and most likely I used the same folder to sync to. If that was the case then yes, these files have indeed been locally deleted at some point. Doesn't fully explain to me why it started by successfully downloading everything from Dropbox, but maybe that's where GPFS comes in?

**Comment by SamSchott** [comment] 2021-02-01 15:14
Hm, that might be possible. It does keep a database with the local file index and content hashes which will persist between installs. This cache *should* be removed when explicitly unlinking, but that might have been flaky two years ago...

This could indeed trigger false deleted events when the local files don't exist at startup (they haven't been downloaded yet) but are still in the index. But it doesn't explain this behaviour:

> I let that run over night. The next day, all my official dropbox and maestral clients look like they have the full original contents again (again, no way of checking precisely). I restart the new maestral to make sure that it's stable now. It starts deleting files again.

**Comment by SamSchott** [comment] 2021-10-29 19:56
Ah, damn, this should have been fixed in #472. @frioux, could you go through the trouble shooting steps in https://github.com/SamSchott/maestral/issues/452#issuecomment-944907916 and post what you get?

**Comment by frioux** [comment] 2021-11-01 16:16
I might be able to get around to it at some point but no ETA.

**Comment by samschott** [comment] 2023-05-16 20:10
Closing since there were multiple improvements to the sync logic since and there are no more user reports of this issue.

**Closed by samschott** 2023-05-16 20:10 UTC
Labels: bug, daemon

**Comment by riconeitzel** [comment] 2023-07-03 10:34
I got bit by it one month ago 😕 I added a new device and installed maestral … hundreds of files were removed. I noticed 3.5 weeks later … just close enough I was able to undelete them via the DBx website. Now I figured out another problem: Many files are 0 bytes size … so they were never deleted.
