### ISSUE TITLE
Synchronize modification dates when downloading for the first time

### ISSUE THREAD

**Issue by vicmarto** [samschott/maestral#991] opened 2023-10-23 00:52 UTC
**Is your feature request related to a problem? Please describe.**
Yesterday I did a full download from Dropbox to my computer, and now all the modification dates are the same: yesterday.

**Describe the solution you'd like**
It would be wonderful if Maestral would also synchronize the modification dates when downloading.

**Additional context**
Thank you very much for the development of Maestral: it is simply thousands of times better than the official client.

**Comment by vicmarto** [comment] 2023-10-26 23:47
Seems it was reported before in #928 as a bug.

**Comment by samschott** [comment] 2024-03-24 12:35
Closing as a duplicate of #928. This was fixed in v1.9.0.

**Closed by samschott** 2024-03-24 12:35 UTC
Labels: enhancement
