### ISSUE TITLE
[BUG] Maestral is not downloading all the files in a folder

### ISSUE THREAD

**Issue by raffaem** [SamSchott/maestral#309] opened 2021-02-10 15:40 UTC
**Describe the bug**
When you add a new folder, only some files and folders are downloaded, not all of them.

All the files and folders are correctly displayed in the "Select Files and Folders" dialog, but are not downloaded

**To Reproduce**
1. Preferences
2. Click on "Files and folders"
3. Check the folder
4. Click on update

**Expected behaviour**
Maestral should download all the files

**System (please complete the following information):**
 - Maestral version: 1.3.2.dev0
 - OS: [e.g. Ubuntu] Ubuntu 20.10
 - Desktop environment: [e.g. Gnome 3.32] GNOME 3.38.1
 - Qt version: 5.14.2
 
**Additional context**
The folder is very big, but Maestral should not do this

**Comment by SamSchott** [comment] 2021-02-11 18:53
This really shouldn't be happening. My best guess is that it might again be problem with resuming the downloads after a drop in the connection. But I'll need some more information to be certain.

1. Could you post the the logs from the the point where you included the folder in the selective sync settings? Log level INFO should be sufficient.
2. What is the output of the CLI command `maestral excluded list`? Are those excluded folders as expected?
3. In the state file `~/.local/share/maestral/maestral.state` there should be field `pending_downloads`. Is anything listed there? If yes, it means that Maestral is aware of the incomplete download and will retry the next time it is resumed.

**Comment by raffaem** [comment] 2021-02-13 10:13
Hello

Sent you the logs.

The folder I have added is not in `maestral excluded list`

In `cat ~/.local/share/maestral/maestral.state`:

```
pending_downloads = []
```

**Comment by SamSchott** [comment] 2021-02-13 16:16
Thanks, this is very helpful! My suspicion was right, this is again related to the connection being lost during the download.

The issue is that despite the download not being completed, it is cleated from the `pending_downloads` list and therefore not resumed later.

Another issue to solve will be resuming the download from where we left off. At the moment, the newly included folder will be indexed from the beginning, as was the case for global indexing. This could in principle be solved by storing the cursor for the download instead of the path in the `pending_downloads` list but there may be a couple of caveats.

**Closed** 2021-02-13 18:13 UTC

**Comment by raffaem** [comment] 2021-02-13 19:08
Thank you!

Can we have an alpha release with that?

------

Sam Schott: "Oh, my Dropbox client works on my 4 files privately held Dropbox folder on fast stable connection. Let's put 1.3 stable out"
Me: "Have zillion of files each few bytes in size. Share folders with zillions of colleagues. Connection drops now and again, changing DNS servers and even ISP in the meantime. Have 2 partitions with different file systems. Have zillions of softwares registered for inotify notifications"
Maestral on me computer: "All processes are stalled. All resources are deadlocked. PC will reboot in kernel panic in 3...2....1..."
Sam Schott: "Damn!"

**Comment by SamSchott** [comment] 2021-02-14 00:00
That is a good summary of the situation 😂 Well, I do have a few more than 4 files, about 20,000, but I personally only use Maestral on fast and stable connections. A full indexing job completes in a few minutes for me.

The automated tests are run on GitHub actions (Microsoft Azure) and therefore also have practically no connection issues. I'll look into possibly testing a dropped connection in an automated way but it won't be straight forward.

In the meantime, I'll push a new dev release. And a new full release should be coming soon as well, probably some time next week.

**Comment by SamSchott** [comment] 2021-02-14 00:17
Ok, v1.3.2.dev0 is out. The best way to resume the unfinished download, without fully excluding and then including the folder again, will be to manually add the path to the `pending_downloads` list in the state file. For example:

```
pending_downloads = ['/path_to_folder']
```

Note that the path should be fully lower case (Dropbox is not case sensitive) and relative to the Dropbox root. Also, make sure to completely quit Maestral before editing the file.

**Comment by raffaem** [comment] 2021-02-15 05:58
It works!

I was able to fully download that folder
