### ISSUE TITLE
Random Sync Pause and Error Bug

### ISSUE THREAD

**Issue by Duhkha8** [samschott/maestral#690] opened 2022-06-01 15:14 UTC
Menu bar access routinely pauses DB sync with no apparent pattern. And, occasionally I receive this message:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/87775724/171438748-c9ec0737-5ae5-4c7d-85d9-293f97f3558c.png">

App and macOS are current.

**Comment by 64kramsystem** [comment] 2022-06-01 16:25
I'm getting those lately (last few days, as of Jun/1/2022) as well. I'm on Linux.

**Comment by scpedicini** [comment] 2022-06-01 23:02
This happens roughly every 10 minutes for me, forcing it to resume seems to fix the issue. If there's no repercussions, maybe have an option in Maestral to just silently ignore this specific error and keep sync in regular state?

**Comment by ufopsi** [comment] 2022-06-02 08:40
Hi, same here on macOS 12.4 (21F79), M1Pro machine.

**Comment by josep11** [comment] 2022-06-02 11:13
Same here with MacOS 12.4 (M1)

**Comment by ehemmete** [comment] 2022-06-02 15:01
Getting slightly more information in the error message today:
`Path: rev:5e075d4b57eaaa09ba411
{"error": "v1_retired"}`

**Comment by samschott** [comment] 2022-06-02 16:47
Duplicate of #683.

**Closed by samschott** 2022-06-02 16:47 UTC
