### ISSUE TITLE
CONSISTENT Data Loss in 1.7.2 & 1.7.3

### ISSUE THREAD

**Issue by blerg-sh** [samschott/maestral#944] opened 2023-07-15 19:21 UTC
**Describe the bug**
I have encountered a number of data loss bugs in 1.7.2 and 1.7.3. Git repos in particular seem to trigger this issue often for me. Some file(s) (always in the .git folder) end up becoming empty (zero bytes) resulting in the git repo being corrupted.

I have dropped back to 1.7.1 on all my machines and no longer encounter this issue. I did still encounter it after rolling back to 1.7.2.

**To Reproduce**
Create and / or work with a git repo inside the syncing folder that has lots of files. Some particular behavior I noticed:
* Computer 1: `rails new` commit
* Computer 1: Maestral reports as synced.
* Computer 2: Corrupted or not a git repo. All code files are synced though.

Inspecting things on dropbox.com shows that not all files in .git are there. Running `git gc --prune=now --aggressive` a bunch of times actually did end up causing all the files to be synced. After working in the repo for a bit, commiting / etc. ON THE OTHER COMPUTER it always ended up showing as corrupted (because not all the .git files are syncing for some reason).

**Expected behaviour**
git repos should not be corrupted by maestral syncing

**System:**
 - Maestral version: 1.7.3 & 1.7.2
 - OS: macOS Ventura 13.4.1
 
**Additional context**

**Comment by github0388** [comment] 2023-07-17 20:10
I have the same issues here and its constantly syncing, please provide a solution to this.
I am a big fan of your work and I do not want to go back to the Dropbox app but this needs to be fixed asap
macOS 13.4.1, Maestral 1.7.3

**Comment by samschott** [comment] 2023-07-21 21:27
I think this may be a duplicate of #925 which will be fixed in the next release.

**Comment by samschott** [comment] 2023-07-24 21:41
Should be fixed in v1.8.0 now.

**Closed by samschott** 2023-07-24 21:41 UTC
Labels: bug
