### ISSUE TITLE
error installing in Arch Linux: python-m2r2 package

### ISSUE THREAD

**Issue by verajosemanuel** [samschott/maestral#709] opened 2022-07-24 09:32 UTC
`===================================== ERRORS =====================================
_______________________ ERROR collecting tests/test_cli.py _______________________
ImportError while importing test module '/home/joe/.cache/yay/python-m2r2/src/m2r2-0.3.2/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cli.py:13: in <module>
    from m2r2 import parse_from_file, main, options
m2r2.py:14: in <module>
    from docutils.core import ErrorString
E   ImportError: cannot import name 'ErrorString' from 'docutils.core' (/usr/lib/python3.10/site-packages/docutils/core.py)
============================ short test summary info =============================
ERROR tests/test_cli.py
!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================ 1 error in 0.17s ================================
==> ERROR: Se produjo un fallo en check().
    Cancelando...
 -> error compilando: python-m2r2
`

**Comment by Shamulwa** [comment] 2022-08-02 13:19
Same here. 

======================================= ERRORS ============================================
_____________________________________ ERROR collecting tests/test_cli.py _____________________________________
ImportError while importing test module '/home/sham/.cache/paru/clone/python-m2r2/src/m2r2-0.3.2/tests/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_cli.py:13: in <module>
    from m2r2 import parse_from_file, main, options
m2r2.py:14: in <module>
    from docutils.core import ErrorString
E   ImportError: cannot import name 'ErrorString' from 'docutils.core' (/usr/lib/python3.10/site-packages/docutils/core.py)
========================================== short test summary info ===========================================
ERROR tests/test_cli.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by samschott** [comment] 2022-08-03 20:03
The error seems to be specific to installing the python-m2r2 package. Curiously, m2r2 is not a dependency of maestral. Do you know how / why this seems to be required on Arch?

Also, could you try installing python-m2r2 separately and see if it succeeds? If it fails, I'd suggest reporting this with the python-m2r2 maintainers.

**Comment by samschott** [comment] 2022-08-17 20:11
Closing since the installation error is caused by maestral itself.

**Closed by samschott** 2022-08-17 20:11 UTC
