### ISSUE TITLE
"Bad Input to API call" error dialog showing up

### ISSUE THREAD

**Issue by danberlyoung** [samschott/maestral#692] opened 2022-06-02 19:28 UTC
I've started seeing an error saying "Bad input to API call" and "{"error": "v1_retired"}" randomly on my Mac. It's a 2015 15 inch MBP running the latest version of Monterey and v1.6.2 of Maestral.

Also about the same time, the sync system pauses itself and shows the circle with two lines in it icon. I then have to select "Resume Syncing" to get it back to normal. 

Thanks!

**Comment by edufelipe** [comment] 2022-06-02 19:47
@danberlyoung Duplicate of #683. Perhaps consider closing this one and adding to that issue?

**Closed** 2022-06-02 20:20 UTC
