### ISSUE TITLE
Random SYNC on MAC

### ISSUE THREAD

**Issue by cotfas** [samschott/maestral#332] opened 2021-02-26 00:07 UTC
Latest version on mac.

It is not the first time I see when my cooler of the mac starts to sound and then I look what it is going on and then I see the Maestral app eating some stuff..

**Comment by cotfas** [comment] 2021-02-26 00:09
gui 142

**Comment by cotfas** [comment] 2021-02-26 00:17
![Screenshot at Feb 26 02-05-37](https://user-images.githubusercontent.com/3340367/109236637-b51ab600-77d8-11eb-9497-3eca2986ebb5.png)
![Uploading Screenshot at Feb 26 02-05-14.png…]()

**Comment by cotfas** [comment] 2021-02-26 00:17
![Screenshot at Feb 26 02-04-25](https://user-images.githubusercontent.com/3340367/109236646-b9df6a00-77d8-11eb-9bc2-9d7b7a18b55f.png)
![Screenshot at Feb 26 02-03-47](https://user-images.githubusercontent.com/3340367/109236648-ba780080-77d8-11eb-8fd6-def312afd43d.png)

**Comment by SamSchott** [comment] 2021-02-26 18:21
That is unusual. Maestral will perform a weekly reindexing of the Dropbox but this should not typically result in download sync only. It will however cause increased CPU usage because content hashes for all files will be computed during the reindexing. The latest release will defer such reindexing when running on battery power.

Is there any pattern to when / how those large uplaod syncs start? Could you post the log output from when this sync starts?

If this should indeed be caused by the regular reindexing jobs, you can both increase the interval for such reindexing and decrease the maximum CPU usage (resulting in throttling of the sync threads) by setting the corresponding config values through the CLI. This is documented in the brand new website [here](https://samschott.github.io/maestral/cli/config).

**Comment by cotfas** [comment] 2021-02-27 09:49
Hello @SamSchott 

"The latest release will defer such reindexing when running on battery power." It was on power, but yes indeed you are right, on power disable it, but take into account that started indexing when were on power and then in the middle of the reindex-process if you switch to battery it should not lost any data.

"Is there any pattern to when" not quite, I do not know, ii noticed it when I do not do intensive tasks and the mac cpu is low/fans are off (this is MBP2020), and sometimes booom, I hear the fans as a power machine 😁.

"how those large uplaod syncs start? " Not sure when but I think they stay like max 1 minute??

"Could you post the log output from when this sync starts?" I think not if it contains sensitive data, will be hard to know when it starts and if I am in an intensive work task I can not do it.

"by setting the corresponding config values through the CLI." I no longer use the CLI version atm, I use only the gui, maybe a settings in the gui config to set how much cpu to throttle for all maestral jobs 😁

Btw: I know it is offtopic, I noticed if I keep the maestral on pause (gui mode) and then restart mac, it starts as sync enabled. 😁

Best regards,
Vlad

**Comment by SamSchott** [comment] 2021-02-28 14:32
@cotfas, thanks for the response and the suggestions.

>  I think not if it contains sensitive data, will be hard to know when it starts and if I am in an intensive work task I can not do it.

Without recognising a pattern or having the logs it will be very hard for me to investigate this. If the log level is set to INFO instead of DEBUG, there will be no confidential data in the logs. The DEBUG output will contain file paths and detailed information about individual sync events and conflict resolution so I would consider it confidential. But there won't be any access tokens or information stored which could comprise the account. Those are only ever stored in the macOS keychain.

If you to have INFO level logs from the past days, those would be very helpful.

>  I no longer use the CLI version atm, I use only the gui, maybe a settings in the gui config to set how much cpu to throttle for all maestral jobs 

Good point. The GUI is currently lagging behind the CLI in features, mostly because the settings pane would need to be redesigned to provide a nicer UI for a larger number of settings. Do note that "installing" the CLI only creates a symlink in `/usr/local/bin` to the CLI executable which is part of the app bundle already. It therefore doesn't require any additional downloads or space on your drive...

> Btw: I know it is offtopic, I noticed if I keep the maestral on pause (gui mode) and then restart mac, it starts as sync enabled. 

True. Changing this to remember a paused state will be very straight forward. It's just a question providing the behaviour that most users would expect. So thanks for the feedback!

**Comment by samschott** [comment] 2023-05-16 20:14
Closing since there a lot of improvements to CPU and bandwidth usage controls in recent releases.

**Closed by samschott** 2023-05-16 20:14 UTC
Labels: bug, daemon
