### ISSUE TITLE
libncursesw.5.dylib: no such file

### ISSUE THREAD

**Issue by frozenpandaman** [samschott/maestral#559] opened 2021-12-28 22:01 UTC
Getting the following message when running `maestral activity` from the CLI:
```
Traceback (most recent call last):
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/runpy.py", line 86, in _run_code
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 41, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 36, in freeze_support_cli
  File "Contents/Resources/app_packages/click/core.py", line 1128, in __call__
  File "Contents/Resources/app_packages/click/core.py", line 1053, in main
  File "Contents/Resources/app_packages/click/core.py", line 1659, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 1395, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 754, in invoke
  File "Contents/Resources/app_packages/maestral/cli.py", line 227, in wrapper
  File "Contents/Resources/app_packages/maestral/cli.py", line 1007, in activity
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/curses/__init__.py", line 13, in <module>
ImportError: dlopen(/Applications/Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.10/lib-dynload/_curses.cpython-310-darwin.so, 0x0002): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.10/lib/libncursesw.5.dylib
  Referenced from: /Applications/Maestral.app/Contents/Resources/Support/Python/Resources/lib/python3.10/lib-dynload/_curses.cpython-310-darwin.so
  Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.10/lib/libncursesw.5.dylib' (no such file), '/usr/lib/libncursesw.5.dylib' (no such file)
```

A GUI popup reading "Application has crashed" also appears, giving the same error but difference traceback:
```
Traceback (most recent call last):
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 41, in <module>
  File "Contents/Resources/app/maestral_cocoa/__main__.py", line 36, in freeze_support_cli
  File "Contents/Resources/app_packages/click/core.py", line 1128, in __call__
  File "Contents/Resources/app_packages/click/core.py", line 1053, in main
  File "Contents/Resources/app_packages/click/core.py", line 1659, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 1395, in invoke
  File "Contents/Resources/app_packages/click/core.py", line 754, in invoke
  File "Contents/Resources/app_packages/maestral/cli.py", line 227, in wrapper
  File "Contents/Resources/app_packages/maestral/cli.py", line 1007, in activity
  File "Contents/Resources/Support/Python/Resources/lib/python3.10/curses/__init__.py", line 13, in <module>
```

Syncing still seems to be working correctly, I just can't view the current progress.

**System:**
 - Maestral version: 1.5.2, installed as a cask via Homebrew
 - Python version: 3.9.9 (have both python@3.9 and python@3.10 installed via brew)
 - OS: macOS 12.1, Apple Silicon (M1) architecture

**Comment by frozenpandaman** [comment] 2021-12-28 22:09
Seems to be related to the curses/ncurses library & #533?

**Comment by samschott** [comment] 2022-01-02 17:01
Yeah, that's a duplicate of #533 and will be fixed in the next release 🤞

**Closed by samschott** 2022-01-02 17:01 UTC
Labels: bug

**Comment by frozenpandaman** [comment] 2022-01-02 19:58
Thanks!
