### ISSUE TITLE
`v1_retired` API error

### ISSUE THREAD

**Issue by Roy-Orbison** [samschott/maestral#683] opened 2022-05-24 02:08 UTC
**Describe the bug**
An alert dialogue from Maestral and a system toast notification both appeared with the same `{"error": "v1_retired"}` message, then Maestral's status icon showed as paused (⏸).

**To Reproduce**
No specific actions, Maestral was running in the background. I had not made any recent changes within the synced root dir.

**Expected behaviour**
Use the current API, I guess.

**System:**
 - Maestral version: 1.6.2
 - Python version: 3.9.7
 - OS: Kubuntu
 - Desktop environment: KDE
 - PyQt version (for Linux GUI): 5.15.4

**Additional context**
Log:
```text
2022-05-24 11:17:53 manager ERROR: Bad input to API call
Traceback (most recent call last):
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/errorhandling.py", line 94, in convert_api_errors
    yield
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/client.py", line 1333, in wait_for_remote_changes
    res = self.dbx.files_list_folder_longpoll(last_cursor, timeout=timeout)
  File "/home/roy/.local/lib/python3.9/site-packages/dropbox/base.py", line 2282, in files_list_folder_longpoll
    r = self.request(
  File "/home/roy/.local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 301, in request
    self.check_and_refresh_access_token()
  File "/home/roy/.local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 369, in check_and_refresh_access_token
    self.refresh_access_token(scope=self._scope)
  File "/home/roy/.local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 403, in refresh_access_token
    self.raise_dropbox_error_for_resp(res)
  File "/home/roy/.local/lib/python3.9/site-packages/dropbox/dropbox_client.py", line 627, in raise_dropbox_error_for_resp
    raise BadInputError(request_id, res.text)
dropbox.exceptions.BadInputError: BadInputError('<REDACTED 32-char hex>', '{"error": "v1_retired"}')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/manager.py", line 843, in _handle_sync_thread_errors
    yield
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/manager.py", line 670, in download_worker
    has_changes = self.sync.wait_for_remote_changes(
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/sync.py", line 2854, in wait_for_remote_changes
    has_changes = client.wait_for_remote_changes(last_cursor, timeout=timeout)
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/client.py", line 1333, in wait_for_remote_changes
    res = self.dbx.files_list_folder_longpoll(last_cursor, timeout=timeout)
  File "/usr/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/roy/.local/lib/python3.9/site-packages/maestral/errorhandling.py", line 96, in convert_api_errors
    raise dropbox_to_maestral_error(exc, dbx_path, local_path)
maestral.exceptions.BadInputError: Bad input to API call. {"error": "v1_retired"}
2022-05-24 11:17:53 manager INFO: Shutting down threads...
2022-05-24 11:17:53 sync INFO: Sync aborted
2022-05-24 11:17:53 manager INFO: Paused
2022-05-24 11:19:43 sync INFO: Sync aborted
2022-05-24 11:19:43 manager INFO: Paused
```

**Comment by To1ne** [comment] 2022-05-24 04:57
The dropbox API v1 is retired since September 2017 already, see https://dropbox.tech/developers/api-v1-deprecated, so I doubt Maestral was still (heavily) depending on that version.

**Comment by Roy-Orbison** [comment] 2022-05-24 05:22
The function that's failing is in the official SDK, and the relevant endpoint is still part of the [V2 API](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-token). This stuff is normally caused by incorrect usage, but it could be an issue with either the the SDK or Dropbox service. :shrug:

**Comment by samschott** [comment] 2022-05-24 08:10
This might just be a temporary glitch on the server side. Let me know if it persists and I'll flag it with the Dropbox support.

**Comment by joshstrange** [comment] 2022-05-24 18:19
I woke up to one of these and I just got another one a minute ago. I'm not saying you need to flag it just yet but I wanted to provide the data point that I've seen this error twice now.

**Comment by frozenpandaman** [comment] 2022-05-24 18:37
Just got this too, fwiw.
<img width="372" src="https://user-images.githubusercontent.com/7245874/170108094-bb48f2bc-f82a-4d96-80ab-e631bef32d87.png">

**Comment by doersino** [comment] 2022-05-24 20:11
Another data point: Popped up for me, too, but now it seems to be working again.

**Comment by samschott** [comment] 2022-05-24 20:12
I've reported the issue to Dropbox and they are looking into it. It appears that something similar occurred previously already.

**Comment by jcguu95** [comment] 2022-05-25 11:41
This issue is gone for me.

**Comment by ubidefeo** [comment] 2022-05-26 14:22
Got it once about 1h ago, then sync paused.
No sync issues in the log.
Resumed sync and it is all working again.
It's one of those snafu, I guess 🤷🏼‍♂️

**Comment by billyadams** [comment] 2022-05-26 15:03
The issue is occurring for me as well. Happened 3 min ago (2022-05-26 09:58 CDT). It also popped up about an hour ago and when I dismissed I then resumed syncing and all was fine until it popped up again. Shows no syncing errors though. 

macOS Monterey 12.3.1, iMac Pro, GUI 1.6.2, daemon 1.6.2

**Comment by glynd** [comment] 2022-05-26 15:11
Just to add a +1 - Looks like Dropbox server issue based on the above

**Comment by joshstrange** [comment] 2022-05-26 15:13
I don't want to spam this issue but I just saw this error for a 3rd time a minute ago. Unless otherwise asked I won't report future incidents if they are scattered (as in: unless it starts to be a real problem). Right now I'll just ignore it and restart sync.

**Comment by stevemuench** [comment] 2022-05-27 08:04
This issue happened to me today on two separate computers (Mac mini M1 and MBP M1 both running 12.4). I selected Resume Synching and it seems to have continued after that.

**Comment by Roy-Orbison** [comment] 2022-05-27 08:09
Closing this as it's just "me too" comments now. @samschott has [already reported it](https://github.com/samschott/maestral/issues/683#issuecomment-1136387062), and it's not this program's fault.

**Comment by samschott** [comment] 2022-05-31 21:10
@Roy-Orbison, I appreciate the intention behind closing this issue. Unfortunately, it just results in new issues being created instead. I'll reopen this as a tracking bug and to report any news to people affected, once there is any.

**Comment by jasongregori** [comment] 2022-05-31 23:36
I know the me-too's are annoying but since not many people have posted in a week I just wanted to let people know it's still happening. I just installed Maestral on a new Mac and I'm hitting this about once an hour. Resuming works fine but I have to resume every time.

**Comment by kurokirasama** [comment] 2022-06-01 00:04
I've been having this issue occasionally, but today has been occurring very frequently, just a few minutes apart, pausing the sync

**Comment by TorontoPolarBear** [comment] 2022-06-01 00:09
I'm having this issue as well, and the frequency has increased significantly in the past few days.

**Comment by Roy-Orbison** [comment] 2022-06-01 00:21
@samschott My understanding is that closing an issue doesn't prevent comments, it just lets people know that there's nothing you can solve because it's not Maestral's fault.

**Comment by mohamednazmi** [comment] 2022-06-01 01:58
Can confirm this is still happening. Appreciate the follow-up from Dropbox, hopefully this will be resolved soon.

**Comment by jmfd** [comment] 2022-06-01 02:27
@Roy-Orbison as someone who deals regularly with dependencies breaking underneath me and (paying) customer fallout, the reality is that a client application is still to a degree responsible for what its dependencies are doing. Assigning fault at Dropbox doesn't discharge Maestral of having the bug.  This brings to light several courses of action that could be taken:

* Better error messaging, especially indicating what operations might have failed, if there is data loss, and a course of action to take
* Automatic restarting or recovery so that a quit/relaunch isn't required (_multiple times a day, today)_
* Possibly using other API calls or workarounds to achieve the same result

Regardless, I mainly wanted to report that this has gotten significantly worse today for whatever reason! I'm happy to send any config info/logs if that can help.

**Comment by theandrewwade** [comment] 2022-06-01 05:59
Data point: Happened quite a bit a week or two ago. Nothing since, but just got it twice today. macOS12.4 and v1.6.2.
"OK" and "Resume sync" makes it go away for a while.

**Comment by nalim** [comment] 2022-06-01 06:08
I got the error today for the first time.

**Comment by Mostxlnt** [comment] 2022-06-01 06:20
This has been happening to me on an M1 Mac Mini MacOS 12.4 for a few weeks. Still happening now, no sync possible.

**Comment by jonaskindler93** [comment] 2022-06-01 07:49
have this issue as well.

**Comment by c0defre4k** [comment] 2022-06-01 08:21
Got this error three times today. Resume syncing fixes it for a few hours. @samschott referring to [your comment](https://github.com/samschott/maestral/issues/683#issuecomment-1136387062) die Dropbox actually fix this on their side? Is it possible to integrate a workaround like automatically resuming on this error?

**Comment by jeanpaulrh** [comment] 2022-06-01 09:42
same here

**Comment by Epizefiri** [comment] 2022-06-01 11:46
I just had it

**Comment by elvo86** [comment] 2022-06-01 12:21
Happening pretty frequently to me now on macOS 12.4 on M1 MBP and i7 MBP. Started noticing it a day or two ago and resume syncing corrected the issue usually, but happened a couple times in a row this morning on both devices.

**Comment by SalmonFOX** [comment] 2022-06-01 13:34
Same here too, on Ubuntu 20.04. Once stop and restart, it runs correctly for a while (say, 1 hour or so?), but soon the error message showed.

**Comment by lekevicius** [comment] 2022-06-01 15:29
<img width="378" alt="Screen Shot 2022-06-01 at 18 24 01" src="https://user-images.githubusercontent.com/218656/171441362-6685d61d-aaef-4f4e-9581-7f158cfec79e.png">

Getting this a lot, just like everyone else. Unpausing just brings it back minutes later.

My first thought, as mentioned by other commenters, was that Maestrial was relying on an API that Dropbox has retired, and that's the end of the client. My first instinct was to visit Maestrial website or this github's README for an announcement (or just an acknowledgement of this error -- it likely affects majority of users).

I would encourage pushing a hotfix to at least mute this particular error and implement a temporary workaround.

**Comment by acantril** [comment] 2022-06-01 19:10
Yeah after recommending this app to a ton of friends, this is a big deal for me
the fact this ticket was closed... (what the **** ?) 
the fact that it's been seen as a minor issue, when it's stopping the app working entirely
Ive had a few cases now (in important situations) where i'm missing files and it turns out my production machine hasn't been syncing ...the second the app is anything BUT 100% reliable, it's 0% reliable.

**Comment by gerrior** [comment] 2022-06-01 23:30
This issue doesn't appear to rise to Dropbox's threshold to report it to the community on their [status page](https://status.dropbox.com). "No incidents reported" between May 21 and Jun 1, including our timeframe.

**Comment by acantril** [comment] 2022-06-02 01:56
I've had this error 4 times since starting work this morning.
In all cases it pops up at the very front of whatever I'm doing.
If i don't click it ... there is a "X" in my menubar.
if i do click it ... its a pause symbol.

In either case, this basically renders the application useless for me, I don't use this term lightly out of annoyance, but if i can't rely 100% on something syncing ... i can't rely on it syncing.

**Comment by xavbart** [comment] 2022-06-02 09:23
Just in case, as I see I have additional details in the error message
```
** Bad input to API call
Path: rev:5e0735f13d8cf8520a5e1
{"error": "v1_retired"}
```
That appears randomly every day, usually when new files are synched. 
Mac OS 10.15.7 - Maestral 1.6.2

**Comment by gmakstutis** [comment] 2022-06-02 09:57
I have seen this error three days in a row. I'm not sure when I occurs because it is usually when I'm not at the computer. There are no sync errors in logs. And, I've not added anything to my dropbox folder for a week. Clicking resume syncing gets things started again.

**Comment by hb9eue** [comment] 2022-06-02 10:30
Just to provide an additional data point. This started happening to me about one week ago. Now it happens in a minute base. I can unpause sync, and about 10min later, I get this error.

I work on a shared project with a lot of changes on the files. So this could cause this to pop up so frequently to me.

**Comment by maiksd** [comment] 2022-06-02 10:37
I'm using this in a every-5-minutes-cronjob as a temporary workaround (resuming works for me, but start/stop is of course also possible this way):

`maestral status | grep -e '^Status.*Paused' && maestral resume`

**Comment by TorontoPolarBear** [comment] 2022-06-02 12:47
Originally downloaded this app as the Mac native alternative to Dropbox which required Rosetta. Looks like Dropbox has updated their Mac version to be native on M1 now so no real reason to keep it, especially if this bug persists. Has anyone switched between them? Anything to be aware of when I switch back?

**Comment by hb9eue** [comment] 2022-06-02 12:56
Actually there are a least two good reasons for maestral, as Dropbox dropped A LOT of functionality from their native client.

* My $home is on NFS. Dropbox removed support for Dropbox folders on network file systems. Not even properly working anymore if there is a softlink pointing to folder outside a network file system so all extended attributes would be available.

* Dropbox introduced a 'number of connected device limit. I was well over that limit and when I once updated a machine, on which the native dropbox client was happily working, dropbox suddenly claimed this is a new machine and locked my client out.

**Comment by tempelmann** [comment] 2022-06-02 17:18
So I did some testing and found a possible work-around, just as I suggested above:

1. I installed Maestral using the given python + pip commands. This installs the source code `/Users/tempi/Library/Python/3.8/lib/python/site-packages/dropbox/dropbox_client.py`

2. I then edited the `dropbox_client.py`, inserting at line 626 the following 3 lines (i.e. before the `else:`and `raise` lines):

```
                elif res.json()['error'] == 'v1_retired':
                	# (TT 02Jun22) ignore, see https://github.com/samschott/maestral/issues/683
                	return
                else:
                    raise BadInputError(request_id, res.text)
```

With this, the v1_retired gets simply ignored, but the synchronization keeps working (while, at the same time, the same error on another computer led to pausing sync again).

**Comment by tempelmann** [comment] 2022-06-02 22:16
> > 1. dropbox_client.py
> 
> Does anybody know if there is a similar fix for anyone that has Maestral installed through the App Bundle?

You mean the Mac installer? That does install only a compiled version of the file ("dropbox_client.pyc"), which one cannot edit that way. Maybe there's a way to replace that with an uncompiled version, but I don't know about that.

**Comment by kurokirasama** [comment] 2022-06-02 22:33
> So I did some testing and found a possible work-around, just as I suggested above:
> 
> 1. I installed Maestral using the given python + pip commands. This installs the source code `/Users/tempi/Library/Python/3.8/lib/python/site-packages/dropbox/dropbox_client.py`
> 2. I then edited the `dropbox_client.py`, inserting at line 626 the following 3 lines (i.e. before the `else:`and `raise` lines):
> 
> ```
>                 elif res.json()['error'] == 'v1_retired':
>                 	# (TT 02Jun22) ignore, see https://github.com/samschott/maestral/issues/683
>                 	return
>                 else:
>                     raise BadInputError(request_id, res.text)
> ```
> 
> With this, the v1_retired gets simply ignored, but the synchronization keeps working (while, at the same time, the same error on another computer led to pausing sync again).
> 
> Could someone else please try this and report whether it works for them, too?

What would be the path in linux?

**Comment by kurokirasama** [comment] 2022-06-03 00:26
> So I did some testing and found a possible work-around, just as I suggested above:
> 
> 1. I installed Maestral using the given python + pip commands. This installs the source code `/Users/tempi/Library/Python/3.8/lib/python/site-packages/dropbox/dropbox_client.py`
> 2. I then edited the `dropbox_client.py`, inserting at line 626 the following 3 lines (i.e. before the `else:`and `raise` lines):
> 
> ```
>                 elif res.json()['error'] == 'v1_retired':
>                 	# (TT 02Jun22) ignore, see https://github.com/samschott/maestral/issues/683
>                 	return
>                 else:
>                     raise BadInputError(request_id, res.text)
> ```
> 
> With this, the v1_retired gets simply ignored, but the synchronization keeps working (while, at the same time, the same error on another computer led to pausing sync again).
> 
> Could someone else please try this and report whether it works for them, too?

I tried this in ubuntu, on the file `.local/lib/python3.8/site-packages/dropbox/dropbox_client.py`, the issue persist, but way less frequently

**Comment by kurokirasama** [comment] 2022-06-03 00:37
> > So I did some testing and found a possible work-around, just as I suggested above:
> > 
> > 1. I installed Maestral using the given python + pip commands. This installs the source code `/Users/tempi/Library/Python/3.8/lib/python/site-packages/dropbox/dropbox_client.py`
> > 2. I then edited the `dropbox_client.py`, inserting at line 626 the following 3 lines (i.e. before the `else:`and `raise` lines):
> > 
> > ```
> >                 elif res.json()['error'] == 'v1_retired':
> >                 	# (TT 02Jun22) ignore, see https://github.com/samschott/maestral/issues/683
> >                 	return
> >                 else:
> >                     raise BadInputError(request_id, res.text)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With this, the v1_retired gets simply ignored, but the synchronization keeps working (while, at the same time, the same error on another computer led to pausing sync again).
> > Could someone else please try this and report whether it works for them, too?
> 
> I tried this in ubuntu, on the file `~/.local/lib/python3.8/site-packages/dropbox/dropbox_client.py`, the issue persist, but way less frequently

EDIT: nope, the problem persist

**Comment by mileusna** [comment] 2022-06-03 08:18
I get this dialog a lot these days. I even switched to native Dropbox client 😇, but it was such a resource hog compared to Maestral, so I switched back to Maestral today, but I got the dialog again already.

MacBookPro M1 Pro (AppleSilicon)

**Comment by acantril** [comment] 2022-06-03 08:20
It started to happen to me multiple times an hour when i'm syncing anything... 
I'm going to have to move away i think - i can't deal with the risk.

**Comment by frozenpandaman** [comment] 2022-06-03 09:50
>Does anybody know if there is a similar fix for anyone that has Maestral installed through the App Bundle?

> You mean the Mac installer? That does install only a compiled version of the file ("dropbox_client.pyc")

Same when installing via Homebrew.

**Comment by ufopsi** [comment] 2022-06-03 12:16
It'd be nice if Maestral simply ignored the error and kept syncing - all automatically behind the stage.

**Comment by spoxies** [comment] 2022-06-03 12:31
It seems possible that a bug that [was 'fixed' in 2018 ](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Suddenly-getting-quot-v1-retired-quot-error/m-p/275637) might be reintroduced on the dropbox end.

A more [recent issue is opend](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Re-Suddenly-getting-quot-v1-retired-quot-error/m-p/599293). I think it might make more sense to place further encouragements/upvotes/information there instead of here (if one feels that it is needed/effective).

The above info is basically what Sam (not tagging him), already wrote.

**Comment by ricir** [comment] 2022-06-03 13:57
> So I did some testing and found a possible work-around, just as I suggested above:
> 
> 1. I installed Maestral using the given python + pip commands. This installs the source code `/Users/tempi/Library/Python/3.8/lib/python/site-packages/dropbox/dropbox_client.py`
> 2. I then edited the `dropbox_client.py`, inserting at line 626 the following 3 lines (i.e. before the `else:`and `raise` lines):
> 
> ```
>                 elif res.json()['error'] == 'v1_retired':
>                 	# (TT 02Jun22) ignore, see https://github.com/samschott/maestral/issues/683
>                 	return
>                 else:
>                     raise BadInputError(request_id, res.text)
> ```
> 
> With this, the v1_retired gets simply ignored, but the synchronization keeps working (while, at the same time, the same error on another computer led to pausing sync again).
> 
> Could someone else please try this and report whether it works for them, too?

Just tried. It seems OK when I create or modify a file but get unexpected error if I delete files from my Dropbox folder, 

![image](https://user-images.githubusercontent.com/52215524/171868626-06973c17-9b00-4a02-bf33-170b26ea5b8a.png)

**Closed** 2022-06-03 23:28 UTC
Labels: bug

**Comment by samschott** [comment] 2022-06-04 00:44
Quick update: The problem still persists server-side but I've tried to mitigate it now by retrying the failing refresh token calls up to five times. Since "only" about 10% of calls are failing, and rarely consecutively, this retry logic should fix the symptoms, however not the cause.

**Comment by frozenpandaman** [comment] 2022-06-07 04:58
FWIW I just got the error once more, running v1.6.3.

**Comment by samschott** [comment] 2022-06-07 07:50
That's surprising. Calls which raise this error are now retired up to 5 times before it is propagated to the user. This indicates things getting worse on the Dropbox side.

**Comment by rmaspero** [comment] 2022-06-07 08:00
I just updated and restarted the sync and got the error within 5 minutes again. Wonder if it is something to with how Dropbox have recently rearranged how Business account folders are structured, that is triggering the error more often?

**Comment by slifty** [comment] 2022-06-07 14:58
Just wanted to re-up a note by ricir above, which is that folks should absolutely be posting on the [Dropbox Issue](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Re-Suddenly-getting-quot-v1-retired-quot-error/m-p/599293) <-- We know Sam is on this as best he can be, so I think this thread is the best place to make noise and get this solved!

**Comment by mileusna** [comment] 2022-06-07 15:01
Zero issues after update couple days ago. 👍

**Comment by Mostxlnt** [comment] 2022-06-07 17:41
Same here, no problems since the new update. Thanks Sam!

**Comment by neugrin** [comment] 2022-06-07 22:55
Thank you, Sam, I'm on Linuxmint, no error, maestral runs fine again. :)

**Comment by samschott** [comment] 2022-06-16 09:39
To close the loop on this, the issue has finally been fixed on the Dropbox side. It took them some time...
