### ISSUE TITLE
UnicodeEncodeError on Python 3.6

### ISSUE THREAD

**Issue by matesmoliere** [samschott/maestral#490] opened 2021-10-26 10:25 UTC
### Discussed in https://github.com/SamSchott/maestral/discussions/489

<div type='discussions-op-text'>

<sup>Originally posted by **matesmoliere** October 26, 2021</sup>
Hi, I get te following message from Maestral notifier:

Traceback (most recent call last):
  File "/home/admin-root/.local/lib/python3.6/site-packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
    yield
  File "/home/admin-root/.local/lib/python3.6/site-packages/maestral/manager.py", line 780, in startup_worker
    self.sync.upload_local_changes_while_inactive()
  File "/home/admin-root/.local/lib/python3.6/site-packages/maestral/sync.py", line 1591, in upload_local_changes_while_inactive
    events, local_cursor = self._get_local_changes_while_inactive()
  File "/home/admin-root/.local/lib/python3.6/site-packages/maestral/sync.py", line 1689, in _get_local_changes_while_inactive
    if is_mignore or not osp.exists(local_path):
  File "/usr/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 55: ordinal not in range(128)

I've tried to stop and start it again, resume syncing,  but no way, still messaging the same issue over and over again.
Best regards,
Antonio
</div>

**Comment by SamSchott** [comment] 2021-11-01 18:33
That all looks correct, characters such as `í` should be properly encoded and decoded. What's more, I cannot reproduce the error using Python 3.6 and the same language settings either. So I'm at a bit of a loss here😕

**Comment by SamSchott** [comment] 2021-11-01 18:37
What does a simple `os.stat(path)` call return in Python with a file name containing an `í` or `\xed` on your system? Does that raise a similar error?

**Comment by matesmoliere** [comment] 2021-11-02 11:03
Hi Sam, I get the following:
admin-root@tardis:~$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, sys
>>> os.stat(Dropbox_Maestral/matematicas/algebra_lineal/geometría_plano_SM-3eso.pdf)
  File "<stdin>", line 1
    os.stat(Dropbox_Maestral/matematicas/algebra_lineal/geometría_plano_SM-3eso.pdf)
                                                                              ^
SyntaxError: invalid syntax
>>>

**Comment by SamSchott** [comment] 2021-11-05 21:47
Oh, you need to put the path in quotes:

```Python
import os, sys

os.stat("Dropbox_Maestral/matematicas/algebra_lineal/geometría_plano_SM-3eso.pdf")
```

**Comment by toddyocum** [comment] 2021-11-08 14:53
fwiw, I recently installed maestral to give it a try over the weekend, and hit what I think is the same issue.

I will see if I can upgrade the python3 version to a new version to fix things.

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 71, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python3.6/logging/handlers.py", line 187, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/site-packages/maestral/logging.py", line 67, in getMessage
    self._safe_msg = sanitize_string(msg)
  File "/usr/local/lib/python3.6/site-packages/maestral/utils/__init__.py", line 118, in sanitize_string
    return os.fsencode(string).decode(errors="replace")
  File "/usr/lib64/python3.6/os.py", line 802, in fsencode
    return filename.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2193' in position 8: ordinal not in range(128)
Call stack:
  File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/maestral/manager.py", line 773, in startup_worker
    self.sync.download_sync_cycle(client)
  File "/usr/local/lib/python3.6/site-packages/maestral/sync.py", line 2841, in download_sync_cycle
    downloaded = self.apply_remote_changes(changes)
  File "/usr/local/lib/python3.6/site-packages/maestral/sync.py", line 3010, in apply_remote_changes
    throttled_log(self._logger, f"Syncing \u2193 {n + 1}/{n_items}")
  File "/usr/local/lib/python3.6/site-packages/maestral/sync.py", line 3789, in throttled_log
    log.log(level=level, msg=msg)
Message: 'Syncing \u2193 1/1'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/maestral/manager.py", line 773, in startup_worker
    self.sync.download_sync_cycle(client)
  File "/usr/local/lib/python3.6/site-packages/maestral/sync.py", line 2841, in download_sync_cycle
    downloaded = self.apply_remote_changes(changes)
  File "/usr/local/lib/python3.6/site-packages/maestral/sync.py", line 3010, in apply_remote_changes
    throttled_log(self._logger, f"Syncing \u2193 {n + 1}/{n_items}")
  File "/usr/local/lib/python3.6/site-packages/maestral/sync.py", line 3789, in throttled_log
    log.log(level=level, msg=msg)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/usr/local/lib/python3.6/site-packages/maestral/logging.py", line 164, in emit
    self.notifier.notify(f"STATUS={record.getMessage()}")
  File "/usr/local/lib/python3.6/site-packages/maestral/logging.py", line 67, in getMessage
    self._safe_msg = sanitize_string(msg)
  File "/usr/local/lib/python3.6/site-packages/maestral/utils/__init__.py", line 118, in sanitize_string
    return os.fsencode(string).decode(errors="replace")
  File "/usr/lib64/python3.6/os.py", line 802, in fsencode
    return filename.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2193' in position 8: ordinal not in range(128)
```

**Comment by matesmoliere** [comment] 2021-11-09 11:24
Hi Sam,

After  os.stat("Dropbox_Maestral/matematicas/algebra_lineal/geometría_plano_SM-3eso.pdf") I get:

os.stat_result(st_mode=33204, st_ino=4462449, st_dev=66309, st_nlink=1, st_uid=1000, st_gid=1000, st_size=1937348, st_atime=1623755207, st_mtime=1368040350, st_ctime=1623755207)

**Comment by Jezmund-Berserker** [comment] 2021-11-09 22:24
Hi - I'm in this camp as well. I have Maestral installed on a couple of new computers (both M1 Macs with MacOS 12.0.1) and I'm getting pretty regular crashes. Here's the most recent Traceback:

Traceback (most recent call last):
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 699, in urlopen
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 445, in _make_request
File "", line 3, in raise_from
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 440, in _make_request
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 1361, in getresponse
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 416, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 409, in _close_conn
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 774, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 491, in _decref_socketios
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 501, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/ssl.py", line 1300, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 495, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/requests/adapters.py", line 439, in send
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 755, in urlopen
File "Contents/Resources/app_packages/urllib3/util/retry.py", line 532, in increment
File "Contents/Resources/app_packages/urllib3/packages/six.py", line 769, in reraise
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 699, in urlopen
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 445, in _make_request
File "", line 3, in raise_from
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 440, in _make_request
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 1361, in getresponse
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 416, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 409, in _close_conn
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 774, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 491, in _decref_socketios
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 501, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/ssl.py", line 1300, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 495, in _real_close
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(41, 'Protocol wrong type for socket'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/client.py", line 126, in convert_api_errors
File "Contents/Resources/app_packages/maestral/client.py", line 488, in get_account_info
File "Contents/Resources/app_packages/dropbox/base.py", line 5219, in users_get_current_account
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 323, in request
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 479, in request_json_string_with_retry
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 592, in request_json_string
File "Contents/Resources/app_packages/requests/sessions.py", line 590, in post
File "Contents/Resources/app_packages/requests/sessions.py", line 542, in request
File "Contents/Resources/app_packages/requests/sessions.py", line 655, in send
File "Contents/Resources/app_packages/requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(41, 'Protocol wrong type for socket'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 627, in download_worker
File "Contents/Resources/app_packages/maestral/manager.py", line 376, in check_and_update_path_root
File "Contents/Resources/app_packages/maestral/manager.py", line 403, in _needs_path_root_update
File "Contents/Resources/app_packages/maestral/client.py", line 488, in get_account_info
File "Contents/Resources/Support/Python/Resources/lib/python3.9/contextlib.py", line 135, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 131, in convert_api_errors
maestral.errors.DropboxConnectionError: Cannot connect to Dropbox. Please check you internet connection and try again later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Contents/Resources/app_packages/maestral/manager.py", line 795, in _handle_sync_thread_errors
File "Contents/Resources/app_packages/maestral/manager.py", line 640, in download_worker
File "Contents/Resources/app_packages/maestral/client.py", line 374, in __exit__
File "Contents/Resources/app_packages/maestral/client.py", line 368, in close
File "Contents/Resources/app_packages/dropbox/dropbox_client.py", line 701, in close
File "Contents/Resources/app_packages/requests/sessions.py", line 747, in close
File "Contents/Resources/app_packages/requests/adapters.py", line 325, in close
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 222, in clear
File "Contents/Resources/app_packages/urllib3/_collections.py", line 100, in clear
File "Contents/Resources/app_packages/urllib3/poolmanager.py", line 173, in 
File "Contents/Resources/app_packages/urllib3/connectionpool.py", line 492, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/http/client.py", line 933, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 501, in close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/ssl.py", line 1300, in _real_close
File "Contents/Resources/Support/Python/Resources/lib/python3.9/socket.py", line 495, in _real_close
OSError: [Errno 41] Protocol wrong type for socket

**Comment by toddyocum** [comment] 2021-11-10 00:53
To follow up, as you suspected, an upgrade to python from 3.6 to 3.8 fixed the issue

I installed anaconda for Linux to get python 3.8

**Comment by woofingcough** [comment] 2021-12-10 02:18
I'm having the exact same problem and I use macOS Monterey on an M1 Macbook Pro.

**Comment by Jezmund-Berserker** [comment] 2021-12-10 02:24
> @Jezmund-Berserker Your error looks like it is a "Protocol wrong type for socket" which looks more like what I've hit in #549 . By any chance are you running a system-wide ad blocker or VPN like AdGuard? I suspect that might be a trigger with mine.

Very likely so. I've since set up a new computer so I can't confirm 100%, but I may mell have been using AdGuard on that computer. I found it to be responsible for some other issues as well, so I did not install it on the new computer and I haven't had any issues since the switch.

**Comment by Jezmund-Berserker** [comment] 2021-12-10 02:25
> I'm having the exact same problem and I use macOS Monterey on an M1 Macbook Pro.

Are you using Adguard or a system-wide VPN?

**Comment by woofingcough** [comment] 2021-12-10 02:27
> > I'm having the exact same problem and I use macOS Monterey on an M1 Macbook Pro.
> 
> Are you using Adguard or a system-wide VPN?

Yes, yes I do. How could you tell?

**Comment by Jezmund-Berserker** [comment] 2021-12-10 02:29
> > > I'm having the exact same problem and I use macOS Monterey on an M1 Macbook Pro.
> > 
> > 
> > Are you using Adguard or a system-wide VPN?
> 
> Yes, yes I do. How could you tell?

You'll be a great test case for @jmfd 's theory, which fits with my case too. Uninstall Adguard, run for a couple of days, and see if the problem goes away.

**Comment by woofingcough** [comment] 2021-12-10 02:31
> > > > I'm having the exact same problem and I use macOS Monterey on an M1 Macbook Pro.
> > > 
> > > 
> > > Are you using Adguard or a system-wide VPN?
> > 
> > 
> > Yes, yes I do. How could you tell?
> 
> You'll be a great test case for @jmfd 's theory, which fits with my case too. Uninstall Adguard, run for a couple of days, and see if the problem goes away.

Will try!

**Comment by jostyee** [comment] 2021-12-10 03:05
@jmfd have the same issue while AdGuard running, but I've checked that Maestral is not in it's filter application list

**Comment by jmfd** [comment] 2021-12-11 01:02
@jostyee My understanding is that AdGuard runs a local VPN, so even if something is on the blocklist network traffic is still going to get routed through AdGuard as long as it is enabled.  Therefore I think the issue isn't about a specific state, but a change in overall VPN state such as when logging into your account after a restart or manual AdGuard enable/disable changes. My theory based on this and looking at the backtrace would be that the OS network conditions are changing, and the python libraries Maestral uses either aren't coping properly or Maestral could do more work to workaround this. (Just a guess at this point)

**Comment by samschott** [comment] 2023-05-16 20:26
Closing since Python 3.6 is no longer supported.

**Closed by samschott** 2023-05-16 20:26 UTC
Labels: bug, daemon
